import React, { createContext, useContext, useState, useEffect } from 'react';
import { speech } from '../services/speech';
import { LanguageOption } from '../types';

export type { LanguageOption };
export type FontSizeOption = 'normal' | 'large' | 'extra-large';

interface AccessibilityContextType {
  fontSize: FontSizeOption;
  setFontSize: (size: FontSizeOption) => void;
  highContrast: boolean;
  setHighContrast: (val: boolean) => void;
  voiceAssistance: boolean;
  setVoiceAssistance: (val: boolean) => void;
  speechRate: number;
  setSpeechRate: (rate: number) => void;
  language: LanguageOption;
  setLanguage: (lang: LanguageOption) => void;
  simpleNavigation: boolean;
  setSimpleNavigation: (val: boolean) => void;
  speakText: (text: string) => void;
  t: (key: string) => string;
}

const AccessibilityContext = createContext<AccessibilityContextType | undefined>(undefined);

const translations: Record<LanguageOption, Record<string, string>> = {
  // English
  en: {
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    todaysActivities: "Today's Activities",
    playMemoryGame: 'Play Memory Game',
    startGame: 'Start Game',
    gameDesc: 'Enjoy soothing puzzles designed to keep your mind vibrant and sharp at your own pace.',
    myMemories: 'My Memories',
    openPhotoBook: 'Open Photo Book',
    memoriesDesc: 'Flip through photos of family trips, dear friends, and treasured memories.',
    voiceCameraAI: 'Voice & Camera AI',
    voiceCameraDesc: 'Check reminders, identify pill bottles or clocks via camera, and speak naturally with your friendly companion.',
    askAI: 'Ask AI Companion',
    myReminders: 'My Reminders',
    viewAllReminders: 'View All Reminders',
    remindersDesc: 'Stay on track with gentle medication times, hydration sips, and daily tasks.',
    allDone: 'All reminders completed for now',
    todaysProgress: "Today's Progress",
    memory: 'Memory',
    attention: 'Attention',
    recall: 'Recall',
    overallHealth: 'Cognitive Score',
    adaptiveLevel: 'Challenge Level',
    easy: 'Gentle (Easy)',
    medium: 'Balanced (Medium)',
    hard: 'Advanced (Hard)',
    voiceActive: 'Voice Help Active',
    readAloud: 'Read Aloud',
    audioHelp: 'Audio Help',
    listening: 'Listening...',
    tapToSpeak: 'Tap to Speak',
    disclaimer: 'MindCare is an assistive memory and cognitive training platform. It is not intended to diagnose dementia or replace professional medical care.',
    patientOverview: 'Patient Overview',
    gamePerformance: 'Game Performance',
    progressTrends: 'Progress Trends',
    memoryBook: 'Memory Book',
    reminders: 'Reminders',
    addMemory: 'Add New Memory',
    createReminder: 'Create Reminder',
    caregiverDashboard: 'Caregiver Dashboard',
    patientDashboard: 'Patient Dashboard',
    caregiverPortal: 'Caregiver Companion Portal',
    monitoringAndCare: 'Monitoring & Care for',
    caregiverSubtitle: 'Track cognitive gaming performance, adjust adaptive challenge levels, enrich the memory album, and schedule gentle daily reminders.',
    activePatient: 'Active Patient',
    adaptiveDifficulty: 'Adaptive Challenge Level',
    gentle: 'Gentle',
    balanced: 'Balanced',
    advanced: 'Advanced',
    signOut: 'Sign Out',
    gameAnalyticsTrends: 'Game Analytics & Trends',
    clinicalPerformanceReport: 'Clinical Performance Report',
    scheduleReminders: 'Schedule & Reminders',
    careInsightsAISummary: 'Care Insights & AI Summary',
    overallCognitiveIndex: 'Overall Cognitive Index',
    visualRetention: 'Visual Recall & Retention',
    avgProcessingSpeed: 'Avg Processing Speed',
    routineAdherenceRate: 'Routine Adherence Rate',
    compositeIndexDesc: 'Composite cognitive health & retention index',
    retentionDesc: 'Photo & pattern association accuracy',
    processingSpeedDesc: 'Average response reaction per game item',
    adherenceDesc: 'Hydration, chores, and medication completion',
    clinicalAssessmentHeading: 'AI Cognitive Assessment & Clinical Trends',
    clinicalAssessmentSub: 'AI evaluation of game performance, mistake patterns, and routine engagement.',
    listenAloud: 'Listen Aloud',
    stopVoice: 'Stop Voice',
    copySummary: 'Copy Summary',
    exportPrintReport: 'Export / Print Report',
    cognitiveDomainBreakdown: 'Cognitive Domain Breakdown',
    visualMemory: 'Visual Memory',
    workingMemory: 'Working Memory',
    executiveFunction: 'Executive Function',
    processingSpeed: 'Processing Speed',
    observedStrengths: 'Observed Cognitive Strengths',
    areasToSupport: 'Areas Recommended for Support',
    clinicalRecommendations: 'Caregiver Actionable Recommendations',
    accuracyProgressTrend: 'Accuracy & Score Progression Trend',
    responseTimeBySession: 'Response Time by Session (Seconds)',
    recentSessionLog: 'Recent Session Log',
    sessionsLogged: 'Sessions Logged',
    allGames: 'All Games',
    filterByGame: 'Filter by Game',
    dateTime: 'Date & Time',
    cognitiveGame: 'Cognitive Game',
    difficulty: 'Difficulty',
    score: 'Score',
    accuracy: 'Accuracy',
    responseTime: 'Response Time',
    mistakes: 'Mistakes',
    patientMemoryBook: 'Patient Memory Book',
    memoryBookSubtitle: 'Add photos and stories to support memory retrieval and comfort.',
    addTaskReminder: 'Add Task / Reminder',
    testReminderMelody: 'Test Reminder Melody 🎵',
    stopMelody: 'Stop Melody',
    markDone: 'Mark Done',
    markIncomplete: 'Mark Incomplete',
    delete: 'Delete',
    urgent: 'Urgent',
    melodySong: 'Melody Song',
    noRemindersScheduled: 'No tasks or reminders scheduled for this patient.',
    saveMemory: 'Save Memory',
    cancel: 'Cancel',
    backToDashboard: 'Back to Dashboard',
    improving: 'Improving',
    stable: 'Stable',
    needsAttention: 'Needs Attention',
    familyEmergency: 'Family & Caregiver Contacts',
    callDoctor: 'Call Dr. Chen',
    callDaughter: 'Call Daughter (Sarah)',
    needHelpAnytime: 'Need assistance? Tap any button above to immediately reach family or your physician.',
    tapAnyCard: 'Tap any card to start',
    patientLocation: 'Patient Location & Safe Zone',
    locationTracking: 'Location Tracking',
    liveLocation: 'Live Location',
    insideSafeZone: 'Inside Safe Zone — Safe at Home',
    outsideSafeZone: 'Outside Safe Zone — Wandering Alert',
    viewOnGoogleMaps: 'Open Google Maps',
    getDirections: 'Get Directions',
    pingLocationNow: 'Ping Device Now',
    pushedFreshLocation: 'Fresh GPS coordinates retrieved successfully',
    safeZoneRadius: 'Safe Geofence Perimeter',
    deviceBattery: 'Battery Level',
    gpsAccuracy: 'GPS Accuracy',
    lastLocationUpdate: 'Updated',
    recentLocationHistory: 'Recent Location Breadcrumbs & Check-ins',
    patientProtectedByTracking: 'Safe Zone Tracking Active',
    locationSharedWithCaregiver: 'Your location is securely monitored by your family and caregiver.',
    safeAtHome: 'Safe at Home',
    switchPatient: 'Switch Patient',
    language: 'Language',
    selectLanguage: 'Select Language',
    accessibility: 'Accessibility',
    textSize: 'Text Size',
    highContrast: 'High Contrast',
    voiceAssistance: 'Voice Assistance',
    simpleNavigation: 'Simple Navigation',
    seniorPatientCompanion: 'Senior & Patient Companion',
    caregiverFamilyPortal: 'Caregiver & Family Portal',
    activeSession: 'Active Session',
    signIn: 'Sign In',
    createAccount: 'Create Account',
    accountAuthDb: 'Account & Database',
    memoryCognitiveCompanion: 'Memory & Cognitive Companion',
    // Photos & Custom Memory
    addTreasuredPhoto: 'Add Treasured Photo',
    addPhotoModalTitle: 'Add Photo for Patient',
    addPhotoModalSub: 'Adding photos to memory book helps spark emotional recognition and comfort.',
    uploadCustomPhoto: 'Upload Custom Photo',
    choosePhotoDevice: 'Select Photo from Your Device',
    photoTitle: 'Photo Title',
    personInPhoto: 'Person in Photo (Optional)',
    relationship: 'Relationship',
    eraOrDate: 'Time / Era (Optional)',
    memoryDescription: 'Memory Story or Recognition Cue',
    saving: 'Saving...',
    photoUploadedSuccess: 'Photo added to memories successfully',
    photoUploadDrop: 'Click to select a photo, or drag and drop here',
    webPhotoUrl: 'Photo Web Link / URL',
    curatedPresets: 'Curated Presets',
    sparkRecognition: 'Write a short description or cue to spark recognition.',
    cherishedAlbum: 'Cherished Album',
    personalMemoryBook: 'My Personal Memory Book',
    personalMemoryBookDesc: 'A comforting collection of the people, moments, and places closest to your heart. Tap any photo to hear their story.',
    listenOverview: 'Listen to Overview',
    time: 'Time',
    needHelp: 'Need Help?',
    homeDashboard: 'Home Dashboard',
    // Songs & Music Therapy
    relaxingSongs: 'Relaxing Songs & Music',
    musicTherapy: 'Music Therapy',
    listenSongs: 'Listen to Songs',
    songsDesc: 'Listen to beloved classical melodies, comforting oldies, nature sounds, or upload and play any song you want.',
    uploadCustomSong: 'Add Any Song You Want',
    chooseAudioFile: 'Upload Audio File',
    allSongs: 'All Songs',
    classicalPiano: 'Peaceful Classical',
    goldenOldies: 'Golden Oldies & Nostalgia',
    natureSounds: 'Soothing Nature',
    ambientComfort: 'Ambient Comfort',
    myUploadedSongs: 'My Custom Songs',
    songTitle: 'Song Title',
    artistName: 'Artist / Performer',
    playSong: 'Play Song',
    pauseSong: 'Pause Song',
    nextSong: 'Next Song',
    previousSong: 'Previous Track',
    volume: 'Volume',
    mute: 'Mute',
    unmute: 'Unmute',
    seniorMusicPlayer: 'Senior Comfort Music Player',
    musicTherapyDesc: 'Familiar melodies stimulate procedural memory, reduce anxiety, and evoke joyful reminiscing.',
    bollywoodClassics: 'Bollywood Classics',
    northEastSongs: 'North Eastern Melodies',
    indianClassical: 'Indian Classical & Flute',
    myFavorites: 'My Favorites',
    nowPlaying: 'Now Playing',
    paused: 'Paused',
    tapToPlay: 'Tap to Play',
    selectSongToBegin: 'Select a Song to Begin',
    peacefulMelodies: 'Peaceful Melodies',
    songLibraryPlaylists: 'Song Library & Playlists',
    showingComfortSongs: 'Comfort Songs',
    noSongsInCategory: 'No songs found in this category',
    addSongPrompt: 'Add any song of your choice using the button below or choose another category.',
    readStory: 'Read Story Aloud',
    cognitiveExercises: 'Cognitive Exercises & Games',
    cognitiveExercisesDesc: 'Choose an exercise below. These games stimulate memory, attention, and recall at a gentle, soothing pace with no penalties or timers.',
    memoryMatch: 'Memory Match',
    memoryMatchDesc: 'Turn over cards and match pairs of flowers, pets, and fruits.',
    visualAssociation: 'Visual Association',
    pictureRecall: 'Picture Recall',
    pictureRecallDesc: 'Study charming items, then identify which one was shown.',
    shortTermRecall: 'Short-term Recall',
    numberRecall: 'Number Recall',
    numberRecallDesc: 'Look and listen to digit sequences, then type them with large buttons.',
    auditoryWorkingMemory: 'Auditory & Working Memory',
    patternRecognition: 'Pattern Recognition',
    patternRecognitionDesc: 'Find the repeating rhythm of shapes and colors to fill the question spot.',
    logicalFocus: 'Logical Focus',
    adaptiveSystem: 'Adaptive System',
    playNow: 'Play Now',
    playAgain: 'Play Again',
    backToHub: 'Back to Games Hub',
    restart: 'Restart',
    tries: 'Tries',
    level: 'Level',
    takeYourTime: 'Tap a card to turn it over, then find its matching twin. Take your time!',
    splendidGameComplete: 'Splendid Work! Game Complete!',
    matchedAllCards: 'You matched all the cards successfully.',
    whichItemWasInPictures: 'Which item was in your pictures?',
    chooseMatchingItem: 'Choose the one item that was part of the pictures you just studied.',
    brilliantCorrect: 'Brilliant! You remembered correctly.',
    goodEffort: 'Good effort! The correct answer was',
    nextRound: 'Next Picture Round',
    completeExercise: 'Complete Exercise',
    studyCarefully: 'Study the pictures carefully',
    readyToRecall: 'Ready to recall? Press when you are set.',
    beginRecall: 'Begin Recall',
    rememberTheseNumbers: 'Remember these numbers',
    nowEnterNumbers: 'Now enter the numbers you saw.',
    clear: 'Clear',
    checkAnswer: 'Check Answer',
    whatComesNextInPattern: 'What comes next in the pattern?',
    tapCorrectMissingShape: 'Tap the correct shape below to complete the sequence.',
    allReminders: 'All',
    medications: 'Medication',
    hydration: 'Hydration',
    activity: 'Activity',
    dailyTasks: 'Daily Tasks',
    completedTasks: 'Completed',
    activeReminders: 'Active Reminders',
    addNewReminder: 'Add New Task / Reminder',
    takeWithWater: 'Take with a glass of water',
    dueNow: 'Due Now',
    upcoming: 'Upcoming',
  },

  // Assamese (অসমীয়া) - Assam
  as: {
    goodMorning: 'সুপ্ৰভাত',
    goodAfternoon: 'শুভ অপৰাহ্ন',
    goodEvening: 'শুভ সন্ধিয়া',
    todaysActivities: 'আজিৰ কাম-কাজ',
    playMemoryGame: 'স্মৃতি খেল খেলক',
    startGame: 'খেল আৰম্ভ কৰক',
    gameDesc: 'আপোনাৰ মন সতেজ আৰু সক্ৰিয় কৰি ৰাখিবলৈ শান্তিপূৰ্ণ খেল উপভোগ কৰক।',
    myMemories: 'মোৰ পুৰণি স্মৃতি',
    openPhotoBook: 'ফটো পুথি খোলক',
    memoriesDesc: 'পৰিয়ালৰ পুৰণি ফটো, বন্ধু-বান্ধৱী আৰু সোঁৱৰণী চাওক।',
    voiceCameraAI: 'কণ্ঠ আৰু কেমেৰা এআই',
    voiceCameraDesc: 'দৰবৰ বটল, ঘড়ী চাওক আৰু আপোনাৰ সহায়কৰ সৈতে সহজে কথা পাতক।',
    askAI: 'সহায়কক সোধক',
    myReminders: 'মোৰ সোঁৱৰণী',
    viewAllReminders: 'সকলো সোঁৱৰণী চাওক',
    remindersDesc: 'নিয়মীয়া দৰব আৰু পানী খোৱাৰ সময় মনত ৰাখক।',
    allDone: 'সকলো সোঁৱৰণী সম্পূৰ্ণ হৈছে',
    todaysProgress: 'আজিৰ উন্নতি',
    memory: 'স্মৃতিশক্তি',
    attention: 'মনোযোগ',
    recall: 'পুনৰস্মৰণ',
    overallHealth: 'মানসিক স্থিতি',
    adaptiveLevel: 'প্ৰত্যাহ্বানৰ স্তৰ',
    easy: 'সহজ (Easy)',
    medium: 'মধ্যম (Medium)',
    hard: 'কঠিন (Hard)',
    voiceActive: 'কণ্ঠ সহায়ক সক্ৰিয়',
    readAloud: 'পঢ়ি শুনাওক',
    audioHelp: 'অডিঅ’ সহায়',
    listening: 'শুনি আছোঁ...',
    tapToSpeak: 'কবলৈ স্পৰ্শ কৰক',
    disclaimer: 'মাইণ্ডকেয়াৰ হৈছে এটা সহায়ক স্মৃতি আৰু জ্ঞানমূলক প্ৰশিক্ষণ মঞ্চ। ই কোনো চিকিৎসাৰ বিকল্প নহয়।',
    patientOverview: 'ৰোগীৰ তথ্য',
    gamePerformance: 'খেলৰ প্ৰদৰ্শন',
    progressTrends: 'উন্নতিৰ ধাৰা',
    memoryBook: 'স্মৃতি পুথি',
    reminders: 'সোঁৱৰণী',
    addMemory: 'নতুন স্মৃতি যোগ কৰক',
    createReminder: 'সোঁৱৰণী তৈয়াৰ কৰক',
    caregiverDashboard: 'যত্নকাৰীৰ ডেচবৰ্ড',
    patientDashboard: 'ৰোগীৰ ডেচবৰ্ড',
    caregiverPortal: 'যত্নকাৰী সংগী প’ৰ্টেল',
    monitoringAndCare: 'তত্ত্বাৱধান আৰু যত্ন:',
    caregiverSubtitle: 'খেলৰ প্ৰদৰ্শন পৰ্যবেক্ষণ কৰক, স্মৃতি পুথিত ফটো যোগ কৰক আৰু দিনটোৰ সোঁৱৰণী নিৰ্ধাৰণ কৰক।',
    activePatient: 'বৰ্তমান ৰোগী',
    adaptiveDifficulty: 'খেলৰ জটিলতা নিৰ্বাচন',
    gentle: 'সহজ',
    balanced: 'মধ্যম',
    advanced: 'উন্নত',
    signOut: 'প্ৰস্থান (Sign Out)',
    gameAnalyticsTrends: 'খেলৰ বিশ্লেষণ আৰু ধাৰা',
    clinicalPerformanceReport: 'স্বাস্থ্য প্ৰদৰ্শন ৰিপৰ্ট',
    scheduleReminders: 'সোঁৱৰণী আৰু সময়সূচী',
    careInsightsAISummary: 'এআই যত্ন আৰু পৰামৰ্শ',
    overallCognitiveIndex: 'সামগ্ৰিক স্মৃতি সূচক',
    visualRetention: 'ছবি আৰু স্মৃতিশক্তি',
    avgProcessingSpeed: 'গড় সঁহাৰিৰ গতি',
    routineAdherenceRate: 'দৈনন্দিন কাৰ্য্যসূচী পালন',
    compositeIndexDesc: 'সামগ্ৰিক মানসিক সুস্থতা আৰু ধাৰণ ক্ষমতা',
    retentionDesc: 'ফটো আৰু আৰ্হি চিনাক্তকৰণৰ সঠিকতা',
    processingSpeedDesc: 'প্ৰতিটো খেলত গ্ৰহণ কৰা সময়',
    adherenceDesc: 'পানী খোৱা, দৰব আৰু দৈনন্দিন অভ্যাস',
    clinicalAssessmentHeading: 'এআই মানসিক স্বাস্থ্য মূল্যায়ন',
    clinicalAssessmentSub: 'খেলৰ শুদ্ধতা আৰু ভুলৰ আৰ্হিৰ ওপৰত এআই বিশ্লেষণ।',
    listenAloud: 'পঢ়ি শুনাওক',
    stopVoice: 'কণ্ঠ বন্ধ কৰক',
    copySummary: 'সাৰাংশ কপি কৰক',
    exportPrintReport: 'ৰিপৰ্ট প্ৰিণ্ট / ডাউনলোড',
    cognitiveDomainBreakdown: 'মানসিক ভাগসমূহৰ বিশ্লেষণ',
    visualMemory: 'দৃশ্য স্মৃতি',
    workingMemory: 'কাৰ্যকৰী স্মৃতি',
    executiveFunction: 'কাৰ্যনিৰ্বাহী ক্ষমতা',
    processingSpeed: 'প্ৰক্ৰিয়াকৰণৰ গতি',
    observedStrengths: 'উপলব্ধ শক্তিশালী দিশ',
    areasToSupport: 'সহায়ৰ প্ৰয়োজনীয় দিশ',
    clinicalRecommendations: 'যত্নকাৰীৰ বাবে কাৰ্যকৰী পৰামৰ্শ',
    accuracyProgressTrend: 'শুদ্ধতা আৰু নম্বৰৰ অগ্ৰগতি',
    responseTimeBySession: 'প্ৰতিটো চেছনৰ সঁহাৰি সময়',
    recentSessionLog: 'শেহতীয়া খেলৰ তথ্য',
    sessionsLogged: 'মুঠ খেল সম্পন্ন',
    allGames: 'সকলো খেল',
    filterByGame: 'খেল অনুসৰি বাছক',
    dateTime: 'তাৰিখ আৰু সময়',
    cognitiveGame: 'খেলৰ নাম',
    difficulty: 'স্তৰ',
    score: 'নম্বৰ',
    accuracy: 'শুদ্ধতা',
    responseTime: 'সঁহাৰি সময়',
    mistakes: 'ভুল সংখ্যা',
    patientMemoryBook: 'ৰোগীৰ স্মৃতি পুথি',
    memoryBookSubtitle: 'ৰোগীৰ সুখময় স্মৃতি আৰু শান্তিৰ বাবে ফটো সংগ্ৰহ কৰক।',
    addTaskReminder: 'নতুন সোঁৱৰণী যোগ কৰক',
    testReminderMelody: 'সুৰ পৰীক্ষা কৰক 🎵',
    stopMelody: 'সুৰ বন্ধ কৰক',
    markDone: 'সম্পূৰ্ণ হ’ল',
    markIncomplete: 'অসম্পূৰ্ণ',
    delete: 'ডিলিট',
    urgent: 'জৰুৰী',
    melodySong: 'সুৰ সংগী',
    noRemindersScheduled: 'এই ৰোগীৰ বাবে কোনো সোঁৱৰণী নিৰ্ধাৰণ কৰা হোৱা নাই।',
    saveMemory: 'সংৰক্ষণ কৰক',
    cancel: 'বাতিল কৰক',
    backToDashboard: 'ডেচবৰ্ডলৈ উভতি যাওক',
    improving: 'উন্নতি হৈছে',
    stable: 'স্থিৰ',
    needsAttention: 'মনোযোগৰ প্ৰয়োজন',
    familyEmergency: 'পৰিয়াল আৰু চিকিৎসকৰ যোগাযোগ',
    callDoctor: 'ডাঃ সেনক ফোন কৰক',
    callDaughter: 'জীয়াৰী (চাৰা)ক ফোন কৰক',
    needHelpAnytime: 'কোনো সহায় লাগিলে ওপৰৰ বুটামত টিপি পৰিয়াল বা চিকিৎসকৰ সৈতে কথা পাতক।',
    tapAnyCard: 'আৰম্ভ কৰিবলৈ যিকোনো কাৰ্ডত স্পৰ্শ কৰক',
    bollywoodClassics: 'বলিউড চিৰসেউজ গীত',
    northEastSongs: 'উত্তৰ-পূবৰ লোকগীত আৰু সুৰ',
    indianClassical: 'ভাৰতীয় শাস্ত্ৰীয় আৰু বাঁহী',
    myFavorites: 'মোৰ প্ৰিয় গীত',
    nowPlaying: 'বৰ্তমান বাজি আছে',
    paused: 'ৰখোৱা হৈছে',
    tapToPlay: 'শুনিবলৈ স্পৰ্শ কৰক',
    selectSongToBegin: 'আৰম্ভ কৰিবলৈ এটা গীত বাছক',
    peacefulMelodies: 'শান্তিপূৰ্ণ সুৰ',
    songLibraryPlaylists: 'গীতৰ পুথি আৰু সুৰসংগ্ৰহ',
    showingComfortSongs: 'শান্তিপূৰ্ণ গীত',
    noSongsInCategory: 'এই ভাগত কোনো গীত পোৱা নগল',
    addSongPrompt: 'তলৰ বুটাম ব্যৱহাৰ কৰি আপোনাৰ পচন্দৰ যিকোনো গীত যোগ কৰক।',
    readStory: 'কাহিনী পঢ়ি শুনাওক',
    cognitiveExercises: 'মানসিক ব্যায়াম আৰু খেল',
    cognitiveExercisesDesc: 'আপোনাৰ মন শান্ত আৰু সক্ৰিয় ৰাখিবলৈ তলৰ যিকোনো এটা শান্তিপূৰ্ণ খেল বাছক।',
    memoryMatch: 'স্মৃতি খেল (যোৰ মিলোৱা)',
    memoryMatchDesc: 'কাৰ্ড ওলোটাই ফুল, পোহনীয়া জীৱ আৰু ফলৰ যোৰ মিলাওক।',
    visualAssociation: 'দৃশ্যমান চিনাক্তকৰণ',
    pictureRecall: 'ছবি চিনাক্তকৰণ (Picture Recall)',
    pictureRecallDesc: 'ছবিবোৰ মনোযোগেৰে চাওক আৰু পিছত সঠিক ছবিখন চিনাক্ত কৰক।',
    shortTermRecall: 'হ্ৰস্বম্যাদী স্মৃতিশক্তি',
    numberRecall: 'সংখ্যা মনত ৰখা (Number Recall)',
    numberRecallDesc: 'সংখ্যাৰ ক্ৰম চাওক আৰু ডাঙৰ বুটামেৰে টাইপ কৰক।',
    auditoryWorkingMemory: 'কাৰ্যকৰী স্মৃতিশক্তি',
    patternRecognition: 'আৰ্হি চিনাক্তকৰণ (Pattern Recognition)',
    patternRecognitionDesc: 'আকৃতি আৰু ৰঙৰ সঠিক ক্ৰম চিনাক্ত কৰি খালী ঠাই পূৰ কৰক।',
    logicalFocus: 'যৌক্তিক মনোযোগ',
    adaptiveSystem: 'স্বয়ংক্রিয় অভিযোজন প্ৰণালী',
    playNow: 'এতিয়া খেলক',
    playAgain: 'পুনৰ খেলক',
    backToHub: 'খেল মেনুলৈ উভতি যাওক',
    restart: 'পুনৰ আৰম্ভ',
    tries: 'চেষ্টা',
    level: 'স্তৰ',
    takeYourTime: 'কাৰ্ড স্পৰ্শ কৰি সঠিক যোৰ বিচাৰক। শান্ত মনেৰে খেলক!',
    splendidGameComplete: 'অসাধাৰণ! খেল সম্পূৰ্ণ হ’ল!',
    matchedAllCards: 'আপুনি সফলতাৰে সকলো কাৰ্ড মিলালে।',
    whichItemWasInPictures: 'কোনটো ছবি আপোনাৰ মনত আছে?',
    chooseMatchingItem: 'আপুনি অলপ আগতে দেখা ছবিখন নিৰ্বাচন কৰক।',
    brilliantCorrect: 'একেবাৰে সঠিক! অতি সুন্দৰ।',
    goodEffort: 'ভাল প্ৰয়াস! সঠিক উত্তৰ আছিল',
    nextRound: 'পৰৱৰ্তী ৰাউণ্ড',
    completeExercise: 'অনুশীলন সম্পূৰ্ণ',
    studyCarefully: 'ছবিবোৰ মনোযোগেৰে চাওক',
    readyToRecall: 'মনত পেলাবলৈ সাজুনে? প্ৰস্তুত হ’লে ক্লিক কৰক।',
    beginRecall: 'উত্তৰ দিয়া আৰম্ভ কৰক',
    rememberTheseNumbers: 'এই সংখ্যাবোৰ মনত ৰাখক',
    nowEnterNumbers: 'এতিয়া আপুনি দেখা সংখ্যাবোৰ লিখক',
    clear: 'মচি পেলাওক',
    checkAnswer: 'উত্তৰ পৰীক্ষা কৰক',
    whatComesNextInPattern: 'এই আৰ্হিত ইয়াৰ পিছত কি আহিব?',
    tapCorrectMissingShape: 'ক্ৰম সম্পূৰ্ণ কৰিবলৈ সঠিক আকৃতিত স্পৰ্শ কৰক।',
    allReminders: 'সকলো',
    medications: 'দৰব',
    hydration: 'পানী খোৱা',
    activity: 'ব্যায়াম আৰু খোজ কঢ়া',
    dailyTasks: 'দৈনন্দিন কাম',
    completedTasks: 'সম্পূৰ্ণ হ’ল',
    activeReminders: 'সক্ৰিয় সোঁৱৰণী',
    addNewReminder: 'নতুন সোঁৱৰণী যোগ কৰক',
    takeWithWater: 'এগিলাচ পানীৰ সৈতে খাব',
    dueNow: 'এতিয়াৰ সময়',
    upcoming: 'আগন্তুক',
  },

  // Bengali (বাংলা) - Tripura & Assam Barak Valley
  bn: {
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ অপরাহ্ন',
    goodEvening: 'শুভ সন্ধ্যা',
    todaysActivities: 'আজকের কার্যক্রম',
    playMemoryGame: 'মেমরি গেম খেলুন',
    startGame: 'খেলা শুরু করুন',
    gameDesc: 'মন সতেজ ও প্রাণবন্ত রাখতে শান্তিময় ধাঁধা উপভোগ করুন।',
    myMemories: 'আমার স্মৃতিসমূহ',
    openPhotoBook: 'ফটো অ্যালবাম খুলুন',
    memoriesDesc: 'পারিবারিক ভ্রমণের ছবি ও প্রিয় স্মৃতিগুলো দেখুন।',
    voiceCameraAI: 'ভয়েস ও ক্যামেরা এআই',
    voiceCameraDesc: 'ওষুধের বোতল বা ঘড়ি ক্যামেরায় দেখান এবং কথা বলুন।',
    askAI: 'সহায়কের সাথে কথা বলুন',
    myReminders: 'আমার অনুস্মারক',
    viewAllReminders: 'সকল অনুস্মারক দেখুন',
    remindersDesc: 'ওষুধ গ্রহণ ও পানি পানের সঠিক সময় মনে রাখুন।',
    allDone: 'সব অনুস্মারক সম্পন্ন হয়েছে',
    todaysProgress: 'আজকের অগ্রগতি',
    memory: 'স্মৃতিশক্তি',
    attention: 'মনোযোগ',
    recall: 'পুনরুদ্ধার',
    overallHealth: 'কগনিটিভ স্কোর',
    adaptiveLevel: 'কঠিনতার মাত্রা',
    easy: 'সহজ (Easy)',
    medium: 'মাঝারি (Medium)',
    hard: 'উন্নত (Hard)',
    voiceActive: 'ভয়েস সহায়ক সক্রিয়',
    readAloud: 'পড়ে শোনান',
    audioHelp: 'অডিও সহায়তা',
    listening: 'শুনছি...',
    tapToSpeak: 'বলতে স্পর্শ করুন',
    disclaimer: 'মাইন্ডকেয়ার একটি সহায়ক স্মৃতি ও জ্ঞানীয় প্রশিক্ষণ প্ল্যাটফর্ম।',
    patientOverview: 'রোগীর সংক্ষিপ্ত বিবরণ',
    gamePerformance: 'খেলার পারফরম্যান্স',
    progressTrends: 'অগ্রগতির ধারা',
    memoryBook: 'স্মৃতি অ্যালবাম',
    reminders: 'অনুস্মারক',
    addMemory: 'নতুন স্মৃতি যোগ করুন',
    createReminder: 'অনুস্মারক তৈরি করুন',
    caregiverDashboard: 'সেবাদানকারীর ড্যাশবোর্ড',
    patientDashboard: 'রোগীর ড্যাশবোর্ড',
    caregiverPortal: 'কেয়ারগিভার কম্প্যানিয়ন পোর্টাল',
    monitoringAndCare: 'তত্ত্বাবধান ও সেবা:',
    caregiverSubtitle: 'গেমিং পারফরম্যান্স ট্র্যাক করুন, স্মৃতির অ্যালবাম সমৃদ্ধ করুন এবং দৈনিক অনুস্মারক শিডিউল করুন।',
    activePatient: 'বর্তমান রোগী',
    adaptiveDifficulty: 'চ্যালেঞ্জের স্তর নির্বাচন',
    gentle: 'সহজ',
    balanced: 'ভারসাম্যপূর্ণ',
    advanced: 'উন্নত',
    signOut: 'লগআউট (Sign Out)',
    gameAnalyticsTrends: 'গেম বিশ্লেষণ ও ট্রেন্ডস',
    clinicalPerformanceReport: 'ক্লিনিক্যাল পারফরম্যান্স রিপোর্ট',
    scheduleReminders: 'শিডিউল ও অনুস্মারক',
    careInsightsAISummary: 'এআই সেবা অন্তর্দৃষ্টি',
    overallCognitiveIndex: 'সামগ্রিক কগনিটিভ সূচক',
    visualRetention: 'ভিজ্যুয়াল রিটেনশন',
    avgProcessingSpeed: 'গড় প্রতিক্রিয়া গতি',
    routineAdherenceRate: 'রুটিন মেনে চলার হার',
    compositeIndexDesc: 'সামগ্রিক মানসিক স্বাস্থ্য ও ধরে রাখার ক্ষমতা',
    retentionDesc: 'ছবি ও প্যাটার্ন মনে রাখার সঠিকতা',
    processingSpeedDesc: 'প্রতি খেলায় গড় প্রতিক্রিয়া সময়',
    adherenceDesc: 'পানি পান, ওষুধ ও দৈনিক অভ্যাস পালন',
    clinicalAssessmentHeading: 'এআই জ্ঞানীয় মূল্যায়ন ও ক্লিনিক্যাল ট্রেন্ডস',
    clinicalAssessmentSub: 'খেলার ফলাফল ও ভুলের ধরন নিয়ে কৃত্রিম বুদ্ধিমত্তার মূল্যায়ন।',
    listenAloud: 'পড়ে শোনান',
    stopVoice: 'ভয়েস বন্ধ করুন',
    copySummary: 'সারাংশ কপি করুন',
    exportPrintReport: 'রিপোর্ট প্রিন্ট / ডাউনলোড',
    cognitiveDomainBreakdown: 'কগনিটিভ ডোমেইন বিভাজন',
    visualMemory: 'ভিজ্যুয়াল মেমরি',
    workingMemory: 'ওয়ার্কিং মেমরি',
    executiveFunction: 'এক্সিকিউটিভ ফাংশন',
    processingSpeed: 'প্রসেসিং স্পিড',
    observedStrengths: 'পর্যবেক্ষিত শক্তি',
    areasToSupport: 'সহায়তার ক্ষেত্রসমূহ',
    clinicalRecommendations: 'সেবাদানকারীর জন্য কার্যকরী সুপারিশ',
    accuracyProgressTrend: 'সঠিকতা ও স্কোরের অগ্রগতি',
    responseTimeBySession: 'সেশন ভিত্তিক প্রতিক্রিয়া সময়',
    recentSessionLog: 'সাম্প্রতিক সেশন লগ',
    sessionsLogged: 'মোট সেশন লগ',
    allGames: 'সব খেলা',
    filterByGame: 'খেলা অনুযায়ী ফিল্টার',
    dateTime: 'তারিখ ও সময়',
    cognitiveGame: 'কগনিটিভ গেম',
    difficulty: 'কঠিনতা',
    score: 'স্কোর',
    accuracy: 'সঠিকতা',
    responseTime: 'সময়',
    mistakes: 'ভুল',
    patientMemoryBook: 'রোগীর স্মৃতি অ্যালবাম',
    memoryBookSubtitle: 'রোগীর মানসিক প্রশান্তি ও স্মৃতি উদ্দীপনার জন্য ছবি যোগ করুন।',
    addTaskReminder: 'নতুন অনুস্মারক যোগ করুন',
    testReminderMelody: 'সুর টেস্ট করুন 🎵',
    stopMelody: 'সুর থামান',
    markDone: 'সম্পন্ন',
    markIncomplete: 'অসম্পূর্ণ',
    delete: 'মুছুন',
    urgent: 'জরুরি',
    melodySong: 'মেলোডি গান',
    noRemindersScheduled: 'এই রোগীর জন্য কোনো অনুস্মারক নির্ধারণ করা হয়নি।',
    saveMemory: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    backToDashboard: 'ড্যাশবোর্ডে ফিরে যান',
    improving: 'উন্নতি হচ্ছে',
    stable: 'স্থিতিশীল',
    needsAttention: 'মনোযোগ প্রয়োজন',
    familyEmergency: 'পরিবার ও ডাক্তারের জরুরি যোগাযোগ',
    callDoctor: 'ডাক্তার সেনকে কল করুন',
    callDaughter: 'মেয়ে সারাকে কল করুন',
    needHelpAnytime: 'যেকোনো প্রয়োজনে অবিলম্বে পরিবার বা চিকিৎসকের সাথে যোগাযোগ করতে উপরের বাটনে চাপ দিন।',
    tapAnyCard: 'শুরু করতে যেকোনো কার্ডে ট্যাপ করুন',
    bollywoodClassics: 'বলিউড কালজয়ী গান',
    northEastSongs: 'উত্তর-পূর্বের লোকগান ও সুর',
    indianClassical: 'ভারতীয় শাস্ত্রীয় ও বাঁশি',
    myFavorites: 'আমার প্রিয় গান',
    nowPlaying: 'এখন বাজছে',
    paused: 'স্থগিত আছে',
    tapToPlay: 'বাজাতে স্পর্শ করুন',
    selectSongToBegin: 'শুরু করতে একটি গান বেছে নিন',
    peacefulMelodies: 'শান্তিময় সুর',
    songLibraryPlaylists: 'গানের তালিকা ও সুরসংগ্রহ',
    showingComfortSongs: 'শান্তিদায়ক গান',
    noSongsInCategory: 'এই বিভাগে কোনো গান পাওয়া যায়নি',
    addSongPrompt: 'নিজের পছন্দের যেকোনো গান যুক্ত করতে নিচের বোতাম ব্যবহার করুন।',
    readStory: 'গল্প পড়ে শোনান',
    cognitiveExercises: 'জ্ঞানীয় খেলা ও অনুশীলন',
    cognitiveExercisesDesc: 'মন শান্ত ও সতেজ রাখতে নিচের যেকোনো একটি সুন্দর খেলা বেছে নিন।',
    memoryMatch: 'স্মৃতি খেলা (জোড়া মেলানো)',
    memoryMatchDesc: 'কার্ড উল্টে ফুল, পোষা প্রাণী ও ফলের জোড়া মেলান।',
    visualAssociation: 'দৃশ্যমান পরিচিতি',
    pictureRecall: 'ছবি স্মরণ (Picture Recall)',
    pictureRecallDesc: 'ছবিগুলো মনোযোগ দিয়ে দেখুন এবং পরবর্তীতে সঠিক ছবিটি চিহ্নিত করুন।',
    shortTermRecall: 'স্বল্পমেয়াদী স্মৃতি',
    numberRecall: 'সংখ্যা মনে রাখা (Number Recall)',
    numberRecallDesc: 'সংখ্যার ক্রম দেখুন এবং বড় বোতাম দিয়ে টাইপ করুন।',
    auditoryWorkingMemory: 'কার্যকরী স্মৃতিশক্তি',
    patternRecognition: 'প্যাটার্ন শনাক্তকরণ (Pattern Recognition)',
    patternRecognitionDesc: 'আকৃতি ও রঙের সঠিক ক্রম চিনে খালি জায়গা পূরণ করুন।',
    logicalFocus: 'যৌক্তিক মনোযোগ',
    adaptiveSystem: 'স্মার্ট অভিযোজন ব্যবস্থা',
    playNow: 'এখনই খেলুন',
    playAgain: 'আবার খেলুন',
    backToHub: 'খেলা মেনুতে ফিরুন',
    restart: 'পুনরায় শুরু',
    tries: 'প্রচেষ্টা',
    level: 'স্তর',
    takeYourTime: 'কার্ডে স্পর্শ করে সঠিক জোড়া খুঁজুন। ধীরেসুস্থে খেলুন!',
    splendidGameComplete: 'চমৎকার! খেলা সম্পন্ন হয়েছে!',
    matchedAllCards: 'আপনি সফলভাবে সব কার্ড মিলিয়েছেন।',
    whichItemWasInPictures: 'কোন বস্তুটি আপনার ছবিতে ছিল?',
    chooseMatchingItem: 'আপনি একটু আগে যে ছবি দেখেছেন তা বেছে নিন।',
    brilliantCorrect: 'দারুণ! আপনি একদম সঠিক মনে রেখেছেন।',
    goodEffort: 'ভালো চেষ্টা! সঠিক উত্তর ছিল',
    nextRound: 'পরবর্তী রাউন্ড',
    completeExercise: 'অনুশীলন সম্পন্ন',
    studyCarefully: 'ছবিগুলো মনোযোগ দিয়ে দেখুন',
    readyToRecall: 'স্মরণ করতে প্রস্তুত? তৈরি হলে চাপ দিন।',
    beginRecall: 'উত্তর দেওয়া শুরু করুন',
    rememberTheseNumbers: 'এই সংখ্যাগুলো মনে রাখুন',
    nowEnterNumbers: 'এবার আপনি যে সংখ্যাগুলো দেখেছেন তা লিখুন',
    clear: 'মুছুন',
    checkAnswer: 'উত্তর যাচাই করুন',
    whatComesNextInPattern: 'এই প্যাটার্নে পরবর্তীতে কী আসবে?',
    tapCorrectMissingShape: 'ক্রম সম্পন্ন করতে সঠিক আকৃতিতে স্পর্শ করুন।',
    allReminders: 'সবগুলো',
    medications: 'ওষুধপত্র',
    hydration: 'পানি পান',
    activity: 'ব্যায়াম ও হাঁটা',
    dailyTasks: 'দৈনন্দিন কাজ',
    completedTasks: 'সম্পন্ন হয়েছে',
    activeReminders: 'সক্রিয় অনুস্মারক',
    addNewReminder: 'নতুন অনুস্মারক যোগ করুন',
    takeWithWater: 'এক গ্লাস পানির সাথে গ্রহণ করুন',
    dueNow: 'এখনই সময়',
    upcoming: 'আসন্ন',
  },

  // Manipuri (মৈতৈলোন্) - Manipur
  mni: {
    goodMorning: 'য়াইফরে (Good morning)',
    goodAfternoon: 'য়াইফরে অপরাহ্ন',
    goodEvening: 'নুমিদাং য়াইফরে',
    todaysActivities: 'ঙসিগী থবকশিং',
    playMemoryGame: 'মেমোরি শান্নবা',
    startGame: 'শান্নবা হৌবা',
    gameDesc: 'ৱাখল সনা তৌনবা অমসুং নিংশিংবা চেৎশিনহন্নবা শান্নবা।',
    myMemories: 'ঐগী নিংশিংবা',
    openPhotoBook: 'ফোতো লাইরিক হাংদোকপা',
    memoriesDesc: 'ইমুং মনুংগী ফোতো অমসুং হৌখিবা মতমগী নিংশিংবা।',
    voiceCameraAI: 'খোন্থা অমসুং কেমেরা এআই',
    voiceCameraDesc: 'হিদাক ফোতো অমসুং ঘড়ি য়েংবা অমদি মতেং হংবা।',
    askAI: 'এআই সহায়ক হংবা',
    myReminders: 'ঐগী নিংশিংহল্লকপশিং',
    viewAllReminders: 'নিংশিংহল্লকপা খুদিংমক য়েংবা',
    remindersDesc: 'হিদাক চাবা অমসুং ঈশিং থকপা মতম চানা তৌবা।',
    allDone: 'ঙসিগী থবক খুদিং লোইরে',
    todaysProgress: 'ঙসিগী মায়পাকপা',
    memory: 'নিংশিংবা',
    attention: 'মিৎয়েং',
    recall: 'হনজিনবা',
    overallHealth: 'কগনিটিভ স্কোর',
    adaptiveLevel: 'চাংলেপ',
    easy: 'লাইবা (Easy)',
    medium: 'ময়ায় (Medium)',
    hard: 'লুবা (Hard)',
    voiceActive: 'খোন্থোক মতেং য়াওরে',
    readAloud: 'পাবা',
    audioHelp: 'অদিও মতেং',
    listening: 'তাবা...',
    tapToSpeak: 'ঙাংনবা নম্বিয়ু',
    disclaimer: 'মাইন্দকেয়্যার অসি নিংশিং মতেং অমদি কগনিটিব ত্রেনিং প্লেতফোর্মনি।',
    patientOverview: 'অনাবা উবা',
    gamePerformance: 'শান্নবগী মহৈ',
    progressTrends: 'মায়পাকপগী খোঙচৎ',
    memoryBook: 'নিংশিং লাইরিক',
    reminders: 'নিংশিংহল্লকপা',
    addMemory: 'অনৌবা নিংশিংবা হাপচিনবা',
    createReminder: 'নিংশিংহল্লকপা শেম্বা',
    caregiverDashboard: 'কেয়ারগিভার ড্যাশবোর্ড',
    patientDashboard: 'অনাবগী ড্যাশবোর্ড',
    caregiverPortal: 'কেয়ারগিভার কম্পেনিয়ন পোর্তাল',
    monitoringAndCare: 'য়েংশিনবা অমসুং য়োকখৎপা:',
    caregiverSubtitle: 'শান্নবগী মহৈ য়েংবা অমসুং নিংশিংবা হেনগৎহন্নবা থবক শেম্বা।',
    activePatient: 'হৌজিক্কী অনাবা',
    adaptiveDifficulty: 'চাংলেপ খনবা',
    gentle: 'লাইবা',
    balanced: 'ময়ায়',
    advanced: 'লুবা',
    signOut: 'থোকপা (Sign Out)',
    gameAnalyticsTrends: 'শান্নবগী খোঙচৎ অমসুং মহৈ',
    clinicalPerformanceReport: 'ক্লিনিক্যাল রির্পোট',
    scheduleReminders: 'মতম অমসুং নিংশিংহল্লকপা',
    careInsightsAISummary: 'এআই পারামর্শ',
    overallCognitiveIndex: 'অপুনবা কগনিটিভ ইন্দেক্স',
    visualRetention: 'উবা নিংশিংবা',
    avgProcessingSpeed: 'পাউখুম পীবগী খোঙচৎ',
    routineAdherenceRate: 'নিয়ম ইল্লিবা চাং',
    compositeIndexDesc: 'ৱাখলগী অশোই অঙাম অমসুং নিংশিং শক্তি',
    retentionDesc: 'ফোতো অমসুং শক্তম নিংশিংবগী অচুম্বা',
    processingSpeedDesc: 'শান্নবদা মতম লৌবগী চাং',
    adherenceDesc: 'ঈশিং থকপা অমসুং হিদাক চাবগী নিয়ম',
    clinicalAssessmentHeading: 'এআই এসেসমেন্ত অমসুং ত্রেন্দস',
    clinicalAssessmentSub: 'শান্নবগী ফল য়েংদুনা এআইনা পীবা পাউতাক।',
    listenAloud: 'পাদুনা তাবা',
    stopVoice: 'খোন্থোক লেপপা',
    copySummary: 'কপি তৌবা',
    exportPrintReport: 'রিপোর্ট প্রিন্ট তৌবা',
    cognitiveDomainBreakdown: 'কগনিটিভ মশকশিং',
    visualMemory: 'ভিজুয়েল মেমোরি',
    workingMemory: 'ৱার্কিং মেমোরি',
    executiveFunction: 'এক্সিকিউটিভ ফাংশন',
    processingSpeed: 'প্রসেসিং স্পিদ',
    observedStrengths: 'পাঙ্গল লৈবা নাকল',
    areasToSupport: 'মতেং পাংদবা য়াদবা নাকল',
    clinicalRecommendations: 'কেয়ারগিভারগী পাউতাক',
    accuracyProgressTrend: 'চুম্বগী খোঙচৎ',
    responseTimeBySession: 'মতম লৌবগী খোঙচৎ',
    recentSessionLog: 'হন্দক্কী সেশন লগ',
    sessionsLogged: 'সেশন অহেনবা',
    allGames: 'শান্নবা খুদিংমক',
    filterByGame: 'শান্নবগী মখল',
    dateTime: 'তারিখ অমসুং মতম',
    cognitiveGame: 'গেমগী মমিং',
    difficulty: 'চাংলেপ',
    score: 'স্কোর',
    accuracy: 'অচুম্বা',
    responseTime: 'মতম',
    mistakes: 'অশোয়বা',
    patientMemoryBook: 'অনাবগী নিংশিং লাইরিক',
    memoryBookSubtitle: 'অনাবগী ৱাখল নুংঙাইহন্নবা ফোতো হাপচিনবা।',
    addTaskReminder: 'অনৌবা নিংশিংহল্লকপা হাপচিনবা',
    testReminderMelody: 'ঈশৈ টেস্ট তৌবা 🎵',
    stopMelody: 'ঈশৈ লেপপা',
    markDone: 'লোইরে',
    markIncomplete: 'লোইদ্রি',
    delete: 'মুথৎপা',
    urgent: 'য়াম্না মরুওইবা',
    melodySong: 'মেলোদি সং',
    noRemindersScheduled: 'নিংশিংহল্লকপা অমত্তা লৈতে।',
    saveMemory: 'সংরক্ষণ তৌবা',
    cancel: 'তৌরোইদবা',
    backToDashboard: 'ড্যাশবোর্ডদা হল্লকপা',
    improving: 'ফগৎলক্লি',
    stable: 'স্থির ওইবা',
    needsAttention: 'য়েংশিনবা তঙাইফদে',
    familyEmergency: 'ইমুং অমসুং দোক্তরগী ফোন',
    callDoctor: 'দোক্তর চেনদা ফোন তৌবা',
    callDaughter: 'ইচানুপী সারা দা ফোন তৌবা',
    needHelpAnytime: 'মতেং দরকার ওইরগদি মথক্কী বুতন নম্বিয়ু।',
    tapAnyCard: 'হৌনবা কার্দ অমদা নম্বিয়ু',
  },

  // Bodo (बर') - Bodoland, Assam
  brx: {
    goodMorning: 'मोजां फुं',
    goodAfternoon: 'मोजां बेलासै',
    goodEvening: 'मोजां मोनाबिलि',
    todaysActivities: 'दिनैनि खामानि',
    playMemoryGame: 'गोसोखां गेलेनाय',
    startGame: 'गेलेनाय जागाय',
    gameDesc: 'गोसोखौ गोजोन आरो गोरा लाखिनो गेलेनाय आव बाहागो ला।',
    myMemories: 'आंनि गोसोखांथि',
    openPhotoBook: 'फट\' बिजाब खेव',
    memoriesDesc: 'नखरनि गोजाम फट\' आरो गोसोखांथि नाय।',
    voiceCameraAI: 'राव आरो केमेरा ए.आइ.',
    voiceCameraDesc: 'मुली बाथा आरो घडि केमेराव दिनथि आरो रायलाय।',
    askAI: 'ए.आइ. सोंलु',
    myReminders: 'आंनि गोसोखां होनाय',
    viewAllReminders: 'गासै गोसोखां होनाय नाय',
    remindersDesc: 'मुली लोंनाय आरो दै लोंनाय समाव गोसोखां।',
    allDone: 'दिनैनि खामानि जोबबाय',
    todaysProgress: 'दिनैनि जौगानाय',
    memory: 'गोसोखांथि',
    attention: 'नोजोर',
    recall: 'गोसोआव लाबोनाय',
    overallHealth: 'कगनिथिभ स्कोर',
    adaptiveLevel: 'थाखो',
    easy: 'गोरलै (Easy)',
    medium: 'गेजेर (Medium)',
    hard: 'गोब्राब (Hard)',
    voiceActive: 'राव हेफाजाब',
    readAloud: 'फरायना खोनासं',
    audioHelp: 'अडिअ हेफाजाब',
    listening: 'खोनासंगासिनो...',
    tapToSpeak: 'रायनो थु',
    disclaimer: 'माइन्दकेयारआ मोनसे गोसोखांथि हेफाजाब मन्च।',
    patientOverview: 'मोजां नायनाय',
    gamePerformance: 'गेलेनायनि महर',
    progressTrends: 'जौगानाय फारिलाइ',
    memoryBook: 'गोसोखां बिजाब',
    reminders: 'गोसोखां होनाय',
    addMemory: 'गोदान गोसोखांथि फान',
    createReminder: 'गोसोखां होनाय बानाय',
    caregiverDashboard: 'सामलायगिरिनि देसबर्ड',
    patientDashboard: 'मोजांनि देसबर्ड',
    caregiverPortal: 'सामलायगिरि पर्टेल',
    monitoringAndCare: 'सामलायनाय आरो नायदिं:',
    caregiverSubtitle: 'गेलेनायनि महर नाय आरो गोसोखांथि बिजाबआव फट\' फान।',
    activePatient: 'बर्तमान बेरामी',
    adaptiveDifficulty: 'थाखो सायख\':',
    gentle: 'गोरलै',
    balanced: 'गेजेर',
    advanced: 'गोब्राब',
    signOut: 'ओंखारलां (Sign Out)',
    gameAnalyticsTrends: 'गेलेनायनि बिजिरनाय',
    clinicalPerformanceReport: 'देहा बिजिरनाय रिपर्ट',
    scheduleReminders: 'गोसोखां होनाय फारिलाइ',
    careInsightsAISummary: 'ए.आइ. बिबुंथि',
    overallCognitiveIndex: 'गासै गोसोखांथि इन्डेक्स',
    visualRetention: 'नुनाय गोसोखांथि',
    avgProcessingSpeed: 'फिननायनि गोख्रैथि',
    routineAdherenceRate: 'सानफ्रोमबोनि नियम मानिनाय',
    compositeIndexDesc: 'गासै गोसोनि शक्ति आरो गोसोआव दोननाय',
    retentionDesc: 'फट\' आरो दाग सिननि गेबेंथि',
    processingSpeedDesc: 'गेलेनायाव फिन हरनाय समाव लाबोनाय',
    adherenceDesc: 'दै लोंनाय आरो मुली लानाय',
    clinicalAssessmentHeading: 'ए.आइ. देहा बिजिरनाय',
    clinicalAssessmentSub: 'गेलेनायनि गोरोन्थि आरो गेबेंनि सायाव बिजिरनाय।',
    listenAloud: 'खोनासं',
    stopVoice: 'राव दोनथ\'',
    copySummary: 'कपि खालाम',
    exportPrintReport: 'प्रिन्ट रिपर्ट',
    cognitiveDomainBreakdown: 'गोसोनि थाखो बाहागो',
    visualMemory: 'नुनाय गोसोखांथि',
    workingMemory: 'मावनाय गोसोखांथि',
    executiveFunction: 'सामलायनाय शक्ति',
    processingSpeed: 'गोख्रैथि',
    observedStrengths: 'मोजां बाहागो',
    areasToSupport: 'मदद नांगौ बाहागो',
    clinicalRecommendations: 'सामलायगिरिनि थाखाय सुबुरुन',
    accuracyProgressTrend: 'गेबें आरो स्कोर जौगानाय',
    responseTimeBySession: 'फिननायनि सम फारिलाइ',
    recentSessionLog: 'दानियानि गेलेनाय फारि',
    sessionsLogged: 'गासै गेलेनाय',
    allGames: 'गासै गेलेनाय',
    filterByGame: 'गेलेनाय सायख\'',
    dateTime: 'अक्त आरो सम',
    cognitiveGame: 'गेलेनायनि मुं',
    difficulty: 'थाखो',
    score: 'स्कोर',
    accuracy: 'गेबेंथि',
    responseTime: 'सम',
    mistakes: 'गोरोन्थि',
    patientMemoryBook: 'गोसोखां बिजाब',
    memoryBookSubtitle: 'बेरामीनि गोसो गोजोन लाखिनो फट\' फान।',
    addTaskReminder: 'गोदान गोसोखां होनाय बानाय',
    testReminderMelody: 'दामनाय आनजाद 🎵',
    stopMelody: 'दामनाय दोनथ\'',
    markDone: 'जाबाय',
    markIncomplete: 'जायाखै',
    delete: 'दानगार',
    urgent: 'गोनांथार',
    melodySong: 'दामनाय रोजाबनाय',
    noRemindersScheduled: 'जेबो गोसोखां होनाय गैया।',
    saveMemory: 'दोन',
    cancel: 'नेवसि',
    backToDashboard: 'देसबर्डआव थांफिन',
    improving: 'मोजां जालांदों',
    stable: 'थादेरदों',
    needsAttention: 'नोजोर नांगौ',
    familyEmergency: 'नखर आरो डाक्टरनि फन',
    callDoctor: 'डाक्टर सेननो कल हर',
    callDaughter: 'फिसायजो (सारा)नो कल हर',
    needHelpAnytime: 'हेफाजाब नांगौब्ला सा गोजौनि बुथामाव थु।',
    tapAnyCard: 'जागायनो थु',
  },

  // Mizo (Mizo ṭawng) - Mizoram
  lus: {
    goodMorning: 'Chibai zing',
    goodAfternoon: 'Chibai chhun',
    goodEvening: 'Chibai tlai',
    todaysActivities: 'Vawiin Hnathawh turte',
    playMemoryGame: 'Hriat kawh infiamna',
    startGame: 'Infiamna Tan rawh',
    gameDesc: 'Rilru tih thawveng leh hriatna tichak tur infiamna nuam tak.',
    myMemories: 'Ka Thil hriat rengte',
    openPhotoBook: 'Thlalak Bu hawng rawh',
    memoriesDesc: 'Chhungkua leh ṭhiante thlalak leh hriatreng tura duan.',
    voiceCameraAI: 'Aw leh Camera AI',
    voiceCameraDesc: 'Damdawi bur thlalak emaw sana en tir la, AI puitu be rawh.',
    askAI: 'AI Puitu zawt rawh',
    myReminders: 'Ka Hriattirnate',
    viewAllReminders: 'Hriattirna zawng zawng en rawh',
    remindersDesc: 'Damdawi ei hun leh tui in hun hriat reng nan.',
    allDone: 'Vawiin atan a zo vek tawh',
    todaysProgress: 'Vawiin Hmasawnna',
    memory: 'Hriatrengna',
    attention: 'Ngaihtuahna',
    recall: 'Hriatchhuah leh',
    overallHealth: 'Hriatrengna Mark',
    adaptiveLevel: 'Zir san dan',
    easy: 'A awl (Easy)',
    medium: 'A laihawl (Medium)',
    hard: 'A harsa (Hard)',
    voiceActive: 'Aw puitu a inhawng',
    readAloud: 'Chhiar chhuak rawh',
    audioHelp: 'Aw puihna',
    listening: 'Ngaithla mek...',
    tapToSpeak: 'Hmet la tawng rawh',
    disclaimer: 'MindCare hi hriatrengna puitu leh rilru tichak tura duan a ni.',
    patientOverview: 'Damlo Dinhmun',
    gamePerformance: 'Infiamna Thawh dan',
    progressTrends: 'Hmasawnna Kal dan',
    memoryBook: 'Hriatreng Lehkhabu',
    reminders: 'Hriattirnate',
    addMemory: 'Hriatrengna Thawk thar',
    createReminder: 'Hriattirna Siang',
    caregiverDashboard: 'Enkawltu Dashboard',
    patientDashboard: 'Damlo Dashboard',
    caregiverPortal: 'Enkawltu Puitu Portal',
    monitoringAndCare: 'Enkawlna leh Vawn himna:',
    caregiverSubtitle: 'Hriatna tichak tur infiamna dinhmun en la, hriattirna dah rawh.',
    activePatient: 'Enkawl lai Damlo',
    adaptiveDifficulty: 'Harsa dan thlan tur',
    gentle: 'A awl',
    balanced: 'A laihawl',
    advanced: 'A harsa',
    signOut: 'Chhuak rawh (Sign Out)',
    gameAnalyticsTrends: 'Infiamna dinhmun enna',
    clinicalPerformanceReport: 'Hriatna Dinhmun Report',
    scheduleReminders: 'Hun bi leh Hriattirna',
    careInsightsAISummary: 'AI Rawnna leh Hriattirna',
    overallCognitiveIndex: 'Hriatrengna Pumpui Mark',
    visualRetention: 'Hmuh Hriatrengna',
    avgProcessingSpeed: 'Chhanna Rang Lam',
    routineAdherenceRate: 'Ni tin Dan zawm zat',
    compositeIndexDesc: 'Rilru hriselna leh thil hriat theihna zat',
    retentionDesc: 'Thlalak leh thil awmdan hriat dik zat',
    processingSpeedDesc: 'Chhanna pek zung zung theih dan',
    adherenceDesc: 'Damdawi ei leh tui in hun bi zawm dan',
    clinicalAssessmentHeading: 'AI Rilru Tehna leh Dinhmun',
    clinicalAssessmentSub: 'Infiamna atanga damlo hmasawn dan AI teh chhuah.',
    listenAloud: 'Ngaithla rawh',
    stopVoice: 'Aw tawp tir rawh',
    copySummary: 'Copy rawh',
    exportPrintReport: 'Report Print rawh',
    cognitiveDomainBreakdown: 'Rilru lama zirlai hrang hrang',
    visualMemory: 'Mita Hmuh Hriatna',
    workingMemory: 'Hnathawh Rilru',
    executiveFunction: 'Rilru Hman theihna',
    processingSpeed: 'Rilru Rang Lam',
    observedStrengths: 'Ṭhatna lai hmuhte',
    areasToSupport: 'Puih ngaihna laite',
    clinicalRecommendations: 'Enkawltu tana Thurawn',
    accuracyProgressTrend: 'Dik zat hmasawn dan',
    responseTimeBySession: 'Hun hman chhung zat',
    recentSessionLog: 'Infiam hnuhnung berte',
    sessionsLogged: 'Infiam zawh zat',
    allGames: 'Infiamna zawng zawng',
    filterByGame: 'Infiamna hrang thlang rawh',
    dateTime: 'Ni leh Hun',
    cognitiveGame: 'Infiamna hming',
    difficulty: 'Har dan',
    score: 'Mark',
    accuracy: 'Dik zat (%)',
    responseTime: 'Hun',
    mistakes: 'Tihsual',
    patientMemoryBook: 'Damlo Hriatreng Bu',
    memoryBookSubtitle: 'Damlo rilru tihhlim nana thlalak dahna.',
    addTaskReminder: 'Hriattirna thar dah rawh',
    testReminderMelody: 'Rimawi chhin rawh 🎵',
    stopMelody: 'Rimawi tihtawp',
    markDone: 'Zo tawh',
    markIncomplete: 'La zo lo',
    delete: 'Paihna',
    urgent: 'Hmanhmawhthlak',
    melodySong: 'Rimawi Hla',
    noRemindersScheduled: 'Hriattirna engmah a la awm lo.',
    saveMemory: 'Vawng ṭha rawh',
    cancel: 'Sut rawh',
    backToDashboard: 'Dashboard-ah let rawh',
    improving: 'Ṭha chho mek',
    stable: 'Ngai reng',
    needsAttention: 'Ngaihsak ngai',
    familyEmergency: 'Chhungkua leh Doctor biak pawhna',
    callDoctor: 'Dr. Chen be rawh',
    callDaughter: 'Fanau Sarah be rawh',
    needHelpAnytime: 'Puihna i mamawh chuan a chunga button hi hmet rawh.',
    tapAnyCard: 'Tan nan card hi hmet rawh',
  },

  // Khasi (Ka Ktien Khasi) - Meghalaya
  kha: {
    goodMorning: 'Khublei step',
    goodAfternoon: 'Khublei sngi',
    goodEvening: 'Khublei janmiet',
    todaysActivities: 'Ki Kam ba mynta ka Sngi',
    playMemoryGame: 'Ïalehkai Kynmaw Jingmut',
    startGame: 'Sdang ïa ka Jingïalehkai',
    gameDesc: 'Ki jingïalehkai ban pynkhlaiñ ïa ka bor pyrkhat bad kynmaw.',
    myMemories: 'Ki Jingkynmaw jong nga',
    openPhotoBook: 'Plie Kot Dur',
    memoriesDesc: 'Ki dur jong ka ïing ka sem bad ki paralok ba kordor.',
    voiceCameraAI: 'Jingiarap da ka Ktien bad Camera AI',
    voiceCameraDesc: 'Peit dur ki dawai lane baje bad kren bad u AI puitu.',
    askAI: 'Kylli ïa u AI Yarap',
    myReminders: 'Ki Jingpyrkhat kynmaw',
    viewAllReminders: 'Peit lut baroh ki jingpyrkhat',
    remindersDesc: 'Ki por dih dawai bad dih um ba kynmaw.',
    allDone: 'La dep baroh ki kam mynta',
    todaysProgress: 'Ka Jingkiew Mynta ka Sngi',
    memory: 'Jingkynmaw',
    attention: 'Jingsngewthuh',
    recall: 'Kynmaw pat',
    overallHealth: 'Jingsngewbha Rilru',
    adaptiveLevel: 'Kyrdan Jingjynjar',
    easy: 'Ba jem (Easy)',
    medium: 'Pdeng (Medium)',
    hard: 'Ba eh (Hard)',
    voiceActive: 'Jingiarap da ka ktien donkam',
    readAloud: 'Pule jam',
    audioHelp: 'Jingiarap Ktien',
    listening: 'Dang sngap...',
    tapToSpeak: 'Kren da kaba shon',
    disclaimer: 'MindCare ka dei ka lad ban pynkynmaw bad pynkhlaiñ ïa ka bor pyrkhat.',
    patientOverview: 'Ka Jinglong u Nongpang',
    gamePerformance: 'Jingïalehkai ba la leh',
    progressTrends: 'Ka Jingkiew ha ki kam',
    memoryBook: 'Kot Dur Jingkynmaw',
    reminders: 'Ki Jingpyrkhat',
    addMemory: 'Buh dur thymmai',
    createReminder: 'Thoh jingpyrkhat thymmai',
    caregiverDashboard: 'Dashboard u Nongsumar',
    patientDashboard: 'Dashboard u Nongpang',
    caregiverPortal: 'Portal Nongsumar',
    monitoringAndCare: 'Jingsumar bad Jingpeit:',
    caregiverSubtitle: 'Peit ïa ka jinglah jong u nongpang bad buh jingkynmaw sngi.',
    activePatient: 'Nongpang ba sumar',
    adaptiveDifficulty: 'Jied jingeh jong ka jingïalehkai',
    gentle: 'Ba jem',
    balanced: 'Pdeng',
    advanced: 'Ba eh',
    signOut: 'Mih noh (Sign Out)',
    gameAnalyticsTrends: 'Jingbatai halor ka jingïalehkai',
    clinicalPerformanceReport: 'Ka Kaiphod Bor Pyrkhat',
    scheduleReminders: 'Ki Por bad Jingkynmaw',
    careInsightsAISummary: 'Jingai buit AI',
    overallCognitiveIndex: 'Ka Bor Jingkynmaw Baroh',
    visualRetention: 'Kynmaw Dur',
    avgProcessingSpeed: 'Ka Jingkloi ban jubab',
    routineAdherenceRate: 'Jingleh ryntih ki kam',
    compositeIndexDesc: 'Ka jingkhlaiñ ka bor pyrkhat bad kynmaw',
    retentionDesc: 'Jinglah kynmaw dur bad jingshisha',
    processingSpeedDesc: 'Por ba shim ban jubab',
    adherenceDesc: 'Jingdih dawai bad dih um tikna',
    clinicalAssessmentHeading: 'Jingbishar AI halor ka Jinglong Rilru',
    clinicalAssessmentSub: 'Ka jingpeit bniah u AI halor ki jingïalehkai u nongpang.',
    listenAloud: 'Sngap jam',
    stopVoice: 'Sangeh ktien',
    copySummary: 'Copy jingbatai',
    exportPrintReport: 'Print Kaiphod',
    cognitiveDomainBreakdown: 'Ki bynta jong ka bor pyrkhat',
    visualMemory: 'Kynmaw da kaba peit',
    workingMemory: 'Bor Kynmaw Kam',
    executiveFunction: 'Bor Rai Pyrkhat',
    processingSpeed: 'Jingkloi Pyrkhat',
    observedStrengths: 'Ki bynta ba khlaiñ',
    areasToSupport: 'Ki bynta ba donkam jingiarap',
    clinicalRecommendations: 'Jingai buit ïa u Nongsumar',
    accuracyProgressTrend: 'Ka jingkiew ha ka jingshisha',
    responseTimeBySession: 'Por ba shim man ka jingïalehkai',
    recentSessionLog: 'Ki jingïalehkai dang shen',
    sessionsLogged: 'Jingïalehkai ba la dep',
    allGames: 'Baroh ki Jingïalehkai',
    filterByGame: 'Jied katkum ka jingïalehkai',
    dateTime: 'Sngi bad Por',
    cognitiveGame: 'Kyrteng Jingïalehkai',
    difficulty: 'Kyrdan',
    score: 'Mark',
    accuracy: 'Jingshisha (%)',
    responseTime: 'Por',
    mistakes: 'Jingbakla',
    patientMemoryBook: 'Kot Dur u Nongpang',
    memoryBookSubtitle: 'Buh ki dur ba kordor ban pynkmen ïa u nongpang.',
    addTaskReminder: 'Buh jingpyrkhat thymmai',
    testReminderMelody: 'Kynud jingrwai 🎵',
    stopMelody: 'Sangeh jingrwai',
    markDone: 'La dep',
    markIncomplete: 'Ym pat dep',
    delete: 'Pynkynriah',
    urgent: 'Donkam kyrkieh',
    melodySong: 'Jingrwai kynud',
    noRemindersScheduled: 'Ym pat don jingpyrkhat ba la buh.',
    saveMemory: 'Kynshew',
    cancel: 'Sangeh',
    backToDashboard: 'Leit phai sha Dashboard',
    improving: 'Kiew bha',
    stable: 'Skhem',
    needsAttention: 'Donkam jingpeit',
    familyEmergency: 'Jingphone sha ka ïing bad Doctor',
    callDoctor: 'Phone Dr. Chen',
    callDaughter: 'Phone Sarah (Khun)',
    needHelpAnytime: 'Lada donkam jingiarap, shon ïa kine ki button haneng.',
    tapAnyCard: 'Shon ban sdang',
  },

  // Garo (A·chik) - Meghalaya
  grt: {
    goodMorning: 'Pringgipat nambate',
    goodAfternoon: 'Saljatchi nambate',
    goodEvening: 'Attam nambate',
    todaysActivities: 'Da·alni Ka·anirang',
    playMemoryGame: 'Gisik Ra·ani Kal·ani',
    startGame: 'Kal·na a·bachenggo',
    gameDesc: 'Gisik namatna aro bilakatna kal·ani.',
    myMemories: 'Angni Gisik Ra·ani',
    openPhotoBook: 'Photo Kitapko O·bo',
    memoriesDesc: 'Nokdang aro ripengrangni noksa.',
    voiceCameraAI: 'Ku·rang aro Camera AI',
    voiceCameraDesc: 'Sam bitilko ba ghoriko niosa AI-ko sing·bo.',
    askAI: 'AI Dakchaktogipako Sing·bo',
    myReminders: 'Angni Gisik Ra·atani',
    viewAllReminders: 'Gisik ra·atanirangko nina',
    remindersDesc: 'Sam ringani aro chi ringani somoiko gisik ra·atani.',
    allDone: 'Da·alni kamrang matchotaha',
    todaysProgress: 'Da·alni Tang·doani',
    memory: 'Gisik Ra·ani',
    attention: 'Gisik On·ani',
    recall: 'Gisik Ra·pilani',
    overallHealth: 'Gisikni Skor',
    adaptiveLevel: 'Kal·ani Gadang',
    easy: 'Altua (Easy)',
    medium: 'Majingang (Medium)',
    hard: 'Raka (Hard)',
    voiceActive: 'Ku·rang dingtang dongaha',
    readAloud: 'Gam·e poraibo',
    audioHelp: 'Ku·rang dakchaka',
    listening: 'Knaenga...',
    tapToSpeak: 'Agan·na jotbo',
    disclaimer: 'MindCare-ara gisik bilakatani platform ong·a.',
    patientOverview: 'Sagipani gimin',
    gamePerformance: 'Kal·ani Skor',
    progressTrends: 'Namroroani',
    memoryBook: 'Photo Kitap',
    reminders: 'Gisik Ra·atanirang',
    addMemory: 'Gital noksako on·bapilbo',
    createReminder: 'Gital gisik ra·atiko dako',
    caregiverDashboard: 'Ni-rokgipani Dashboard',
    patientDashboard: 'Sagipani Dashboard',
    caregiverPortal: 'Ni-rokgipani Portal',
    monitoringAndCare: 'Sana-banani aro Ni-rokani:',
    caregiverSubtitle: 'Sagipani kal·ani gadangko nina aro gisik ra·ataniko songna.',
    activePatient: 'Da·alo sanna donggipa',
    adaptiveDifficulty: 'Kal·ani Gadangko Seoko',
    gentle: 'Altua',
    balanced: 'Majingang',
    advanced: 'Raka',
    signOut: 'Ong·katbo (Sign Out)',
    gameAnalyticsTrends: 'Kal·ani gimin sandiani',
    clinicalPerformanceReport: 'Gisik Bilakani Report',
    scheduleReminders: 'Somoini Gisik Ra·atani',
    careInsightsAISummary: 'AI-ni ku·patti',
    overallCognitiveIndex: 'Pilak Gisikni Index',
    visualRetention: 'Nika Gisik Ra·ani',
    avgProcessingSpeed: 'Aganchakani Ta·raka',
    routineAdherenceRate: 'Salantin Kamko Ja·rika',
    compositeIndexDesc: 'Pilak gisik bilakani aro ra·ani',
    retentionDesc: 'Noksako ma·siani',
    processingSpeedDesc: 'Aganchakna nangani somoi',
    adherenceDesc: 'Sam aro chi ringani somoi ja·rika',
    clinicalAssessmentHeading: 'AI-ni Gisikko Sandiani',
    clinicalAssessmentSub: 'Kal·aniko niosa AI-ni parakatgipa.',
    listenAloud: 'Knaatbo',
    stopVoice: 'Donbo',
    copySummary: 'Copy ka·bo',
    exportPrintReport: 'Print Report',
    cognitiveDomainBreakdown: 'Gisikni Bakrang',
    visualMemory: 'Nikao gisik ra·ani',
    workingMemory: 'Kam ka·ao gisik',
    executiveFunction: 'Chanchiani bil',
    processingSpeed: 'Ta·rakani bil',
    observedStrengths: 'Bilakgipa bakrang',
    areasToSupport: 'Dakchakna nangani bakrang',
    clinicalRecommendations: 'Ni-rokgipana Ku·pattiani',
    accuracyProgressTrend: 'Tik ong·ani namroroani',
    responseTimeBySession: 'Aganchakani Somoi',
    recentSessionLog: 'Gital Kal·anirang',
    sessionsLogged: 'Kal·ani matchotaha',
    allGames: 'Pilak Kal·ani',
    filterByGame: 'Kal·aniko seokbo',
    dateTime: 'Sal aro Somoi',
    cognitiveGame: 'Kal·ani Bimung',
    difficulty: 'Gadang',
    score: 'Skor',
    accuracy: 'Tik ong·a (%)',
    responseTime: 'Somoi',
    mistakes: 'Gualani',
    patientMemoryBook: 'Sagipani Photo Kitap',
    memoryBookSubtitle: 'Sagipani kusi ong·na noksarangko on·bapilbo.',
    addTaskReminder: 'Gisik ra·atiko on·dapbo',
    testReminderMelody: 'Ring·aniko sulsul knabo 🎵',
    stopMelody: 'Donbo',
    markDone: 'Matchotaha',
    markIncomplete: 'Matchotkuja',
    delete: 'Gimaatbo',
    urgent: 'Nangchongmota',
    melodySong: 'Ring·ani git',
    noRemindersScheduled: 'Gisik ra·atani dongkuja.',
    saveMemory: 'Rikibo',
    cancel: 'Watgalbo',
    backToDashboard: 'Dashboard-ona re·bapilbo',
    improving: 'Namroroenga',
    stable: 'Tik donga',
    needsAttention: 'Ni-rokna nanga',
    familyEmergency: 'Nokdang aro Doctor-ona call ka·na',
    callDoctor: 'Dr. Chen-ona call ka·bo',
    callDaughter: 'Sarah-ona call ka·bo',
    needHelpAnytime: 'Dakchakna nango kosako jotbo.',
    tapAnyCard: 'A·bachenna jotbo',
  },

  // Nepali (नेपाली) - Sikkim & Hill regions
  ne: {
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दिउँसो',
    goodEvening: 'शुभ साँझ',
    todaysActivities: 'आजका गतिविधिहरू',
    playMemoryGame: 'स्मरण खेल खेल्नुहोस्',
    startGame: 'खेल सुरु गर्नुहोस्',
    gameDesc: 'मन ताजा र शान्त राख्न रमाइलो बौद्धिक खेल खेल्नुहोस्।',
    myMemories: 'मेरा सम्झनाहरू',
    openPhotoBook: 'फोटो एल्बम खोल्नुहोस्',
    memoriesDesc: 'परिवारका पुराना फोटोहरू र मिठा सम्झनाहरू हेर्नुहोस्।',
    voiceCameraAI: 'भ्वाइस र क्यामेरा एआई',
    voiceCameraDesc: 'औषधिको बट्टा वा घडी क्यामेरामा देखाउनुहोस् र कुरा गर्नुहोस्।',
    askAI: 'एआई साथीलाई सोध्नुहोस्',
    myReminders: 'मेरा सम्झौताहरू',
    viewAllReminders: 'सबै सम्झनाहरू हेर्नुहोस्',
    remindersDesc: 'औषधि खाने र पानी पिउने समयको याद राख्नुहोस्।',
    allDone: 'आजका सबै कार्यहरू पूरा भए',
    todaysProgress: 'आजको प्रगति',
    memory: 'स्मरणशक्ति',
    attention: 'ध्यान',
    recall: 'पुनःस्मरण',
    overallHealth: 'कग्निटिभ स्कोर',
    adaptiveLevel: 'चुनौती स्तर',
    easy: 'सजिलो (Easy)',
    medium: 'मध्यम (Medium)',
    hard: 'कठिन (Hard)',
    voiceActive: 'आवाज मद्दत सक्रिय',
    readAloud: 'पढेर सुनाउनुहोस्',
    audioHelp: 'अडियो सहायता',
    listening: 'सुन्दैछ...',
    tapToSpeak: 'बोल्न यहाँ छुनुहोस्',
    disclaimer: 'माइन्डकेयर स्मरणशक्ति र बौद्धिक अभ्यासका लागि सहयोगी मञ्च हो।',
    patientOverview: 'बिरामीको विवरण',
    gamePerformance: 'खेलको नतिजा',
    progressTrends: 'प्रगतिको दिशा',
    memoryBook: 'स्मरण पुस्तक',
    reminders: 'सम्झौताहरू',
    addMemory: 'नयाँ सम्झना थप्नुहोस्',
    createReminder: 'नयाँ सम्झौता बनाउनुहोस्',
    caregiverDashboard: 'हेरचाहकर्ताको ड्यासबोर्ड',
    patientDashboard: 'बिरामीको ड्यासबोर्ड',
    caregiverPortal: 'हेरचाहकर्ता पोर्टल',
    monitoringAndCare: 'निगरानी तथा हेरचाह:',
    caregiverSubtitle: 'खेलको नतिजा हेर्नुहोस्, फोटो एल्बम सजाउनुहोस् र तालिका बनाउनुहोस्।',
    activePatient: 'वर्तमान बिरामी',
    adaptiveDifficulty: 'चुनौतीको स्तर चयन गर्नुहोस्',
    gentle: 'सजिलो',
    balanced: 'सन्तुलित',
    advanced: 'कठिन',
    signOut: 'बाहिर निस्कनुहोस् (Sign Out)',
    gameAnalyticsTrends: 'खेल विश्लेषण र प्रवृत्ति',
    clinicalPerformanceReport: 'मानसिक स्वास्थ्य रिपोर्ट',
    scheduleReminders: 'तालिका र सम्झनाहरू',
    careInsightsAISummary: 'एआई सुझाव र विश्लेषण',
    overallCognitiveIndex: 'समग्र मानसिक सूचकांक',
    visualRetention: 'दृश्य स्मरण क्षमता',
    avgProcessingSpeed: 'औसत प्रतिक्रिया गति',
    routineAdherenceRate: 'नियमित कार्य पालना',
    compositeIndexDesc: 'समग्र मानसिक क्षमता र स्मरण शक्ति',
    retentionDesc: 'फोटो र आकार सम्झने शुद्धता',
    processingSpeedDesc: 'प्रतिक्रिया दिन लाग्ने समय',
    adherenceDesc: 'औषधि र पानी पिउने नियम पालना',
    clinicalAssessmentHeading: 'एआई मानसिक परीक्षण र विश्लेषण',
    clinicalAssessmentSub: 'खेलको नतिजा र गल्तीहरूको आधारमा एआई विश्लेषण।',
    listenAloud: 'सुन्नुहोस्',
    stopVoice: 'आवाज बन्द गर्नुहोस्',
    copySummary: 'सारांश कपी गर्नुहोस्',
    exportPrintReport: 'रिपोर्ट प्रिन्ट / डाउनलोड',
    cognitiveDomainBreakdown: 'मानसिक क्षमताका क्षेत्रहरू',
    visualMemory: 'दृश्य स्मरण',
    workingMemory: 'कार्यकारी स्मरण',
    executiveFunction: 'निर्णय क्षमता',
    processingSpeed: 'प्रक्रिया गति',
    observedStrengths: 'राम्रा पक्षहरू',
    areasToSupport: 'सुधार गर्नुपर्ने पक्षहरू',
    clinicalRecommendations: 'हेरचाहकर्ताका लागि सुझावहरू',
    accuracyProgressTrend: 'शुद्धता र स्कोरको प्रगति',
    responseTimeBySession: 'समय अनुसार प्रतिक्रिया गति',
    recentSessionLog: 'हालैका खेलहरूको सूची',
    sessionsLogged: 'कुल खेलिएको संख्या',
    allGames: 'सबै खेलहरू',
    filterByGame: 'खेल अनुसार छान्नुहोस्',
    dateTime: 'मिति र समय',
    cognitiveGame: 'खेलको नाम',
    difficulty: 'स्तर',
    score: 'अङ्क',
    accuracy: 'शुद्धता (%)',
    responseTime: 'समय',
    mistakes: 'गल्ती',
    patientMemoryBook: 'बिरामीको फोटो एल्बम',
    memoryBookSubtitle: 'बिरामीको खुसी र सम्झनाका लागि फोटोहरू थप्नुहोस्।',
    addTaskReminder: 'नयाँ कार्य थप्नुहोस्',
    testReminderMelody: 'धुन सुन्नुहोस् 🎵',
    stopMelody: 'धुन बन्द',
    markDone: 'सम्पन्न भयो',
    markIncomplete: 'अपूर्ण',
    delete: 'हटाउनुहोस्',
    urgent: 'अति जरुरी',
    melodySong: 'सुमधुर धुन',
    noRemindersScheduled: 'कुनै पनि तालिका बनाइएको छैन।',
    saveMemory: 'सुरक्षित गर्नुहोस्',
    cancel: 'रद्द गर्नुहोस्',
    backToDashboard: 'ड्यासबोर्डमा फर्कनुहोस्',
    improving: 'सुधार हुँदैछ',
    stable: 'स्थिर',
    needsAttention: 'ध्यान दिनुपर्ने',
    familyEmergency: 'परिवार र डाक्टरको सम्पर्क',
    callDoctor: 'डा. चेनलाई कल गर्नुहोस्',
    callDaughter: 'छोरी सारालाई कल गर्नुहोस्',
    needHelpAnytime: 'मद्दत चाहिएमा माथिका बटनहरू छुनुहोस्।',
    tapAnyCard: 'सुरु गर्न कुनै पनि कार्ड छुनुहोस्',
  },

  // Nagamese / Ao - Nagaland
  ao: {
    goodMorning: 'Asüng külem (Good morning)',
    goodAfternoon: 'Nikong külem (Good afternoon)',
    goodEvening: 'Aonung külem (Good evening)',
    todaysActivities: 'Tanü Mapa Inyaktsü',
    playMemoryGame: 'Bilemtetba Asaya',
    startGame: 'Asaya Tenzükang',
    gameDesc: 'Shisatsü junga alitsü asoshi shisatsü asaya.',
    myMemories: 'Keni Bilemtetba',
    openPhotoBook: 'Noksa Kaket Lapokang',
    memoriesDesc: 'Kibong noksa aser temba nungi bilemtettsü.',
    voiceCameraAI: 'Ola aser Camera AI',
    voiceCameraDesc: 'Moza poti noksa enokang aser AI den jembir.',
    askAI: 'AI Yarir Dang Asüngdangang',
    myReminders: 'Bilemtettsü Mapang',
    viewAllReminders: 'Mapang ajak reprangang',
    remindersDesc: 'Moza achitsü aser tzü jemtsü bilemtetba.',
    allDone: 'Tanü asoshi ajak tembangogo',
    todaysProgress: 'Tanü Renlokba',
    memory: 'Bilemtetba',
    attention: 'Koma Reprangtsü',
    recall: 'Bilemtettsüba',
    overallHealth: 'Shisatsü Skor',
    adaptiveLevel: 'Tasak Tashi',
    easy: 'Melamela (Easy)',
    medium: 'Alemba (Medium)',
    hard: 'Tasak (Hard)',
    voiceActive: 'Ola yariba lapokogo',
    readAloud: 'Ola agi azüngang',
    audioHelp: 'Ola yariba',
    listening: 'Angadangdar...',
    tapToSpeak: 'Jembitsü asoshi nembang',
    disclaimer: 'MindCare ya shisatsü bilemtetba yaritsü atema lir.',
    patientOverview: 'Shiranger Reprangba',
    gamePerformance: 'Asaya Nung Inyakba',
    progressTrends: 'Renlokba Lenmang',
    memoryBook: 'Noksa Kaket',
    reminders: 'Bilemtettsü Mapang',
    addMemory: 'Noksa tasen enokang',
    createReminder: 'Bilemtettsü tasen yanglutsü',
    caregiverDashboard: 'Anepalur Dashboard',
    patientDashboard: 'Shiranger Dashboard',
    caregiverPortal: 'Anepalur Portal',
    monitoringAndCare: 'Reprangshim aser Anepaluba:',
    caregiverSubtitle: 'Asaya nung shisatsü koma reprangtsü aser mapang lemtetang.',
    activePatient: 'Tang Shiranger',
    adaptiveDifficulty: 'Tasak Tashi Shimang',
    gentle: 'Melamela',
    balanced: 'Alemba',
    advanced: 'Tasak',
    signOut: 'Adokang (Sign Out)',
    gameAnalyticsTrends: 'Asaya Inyakba Reprangba',
    clinicalPerformanceReport: 'Shisatsü Tashi Report',
    scheduleReminders: 'Mapang aser Bilemtettsü',
    careInsightsAISummary: 'AI Shisatsü Pulu',
    overallCognitiveIndex: 'Shisatsü Ajijung Index',
    visualRetention: 'Noksa Bilemtetba',
    avgProcessingSpeed: 'Langzüba Tashi',
    routineAdherenceRate: 'Mapang Shitak Inyakba',
    compositeIndexDesc: 'Shisatsü tashi aser bilemtetba ajak',
    retentionDesc: 'Noksa junga bilemtettsüba',
    processingSpeedDesc: 'Langzütsü atema mapang agiba',
    adherenceDesc: 'Moza achi aser tzü jemba mapang',
    clinicalAssessmentHeading: 'AI Shisatsü Koma Asadangba',
    clinicalAssessmentSub: 'Asaya reprangteter AI-i asadangtsüba.',
    listenAloud: 'Ola agi angashiyang',
    stopVoice: 'Ola anendakjang',
    copySummary: 'Copy süang',
    exportPrintReport: 'Print Report',
    cognitiveDomainBreakdown: 'Shisatsü Atsüngba Lemla',
    visualMemory: 'Noksa Bilemtetba',
    workingMemory: 'Inyaktsü Bilemtetba',
    executiveFunction: 'Lemtetsü Tashi',
    processingSpeed: 'Kara Inyaktsüba',
    observedStrengths: 'Tashi Tajung Aliba',
    areasToSupport: 'Yaritsü Nüngdaka Aliba',
    clinicalRecommendations: 'Anepaluba Asoshi Shisatsü',
    accuracyProgressTrend: 'Shitak Asayaba Renlokba',
    responseTimeBySession: 'Asaya maneni mapang',
    recentSessionLog: 'Tang Asayaba Kaket',
    sessionsLogged: 'Asayaba Tashi',
    allGames: 'Asaya Ajak',
    filterByGame: 'Asaya shimtetang',
    dateTime: 'Anogo aser Mapang',
    cognitiveGame: 'Asaya Tenüng',
    difficulty: 'Tasak',
    score: 'Skor',
    accuracy: 'Shitak (%)',
    responseTime: 'Mapang',
    mistakes: 'Tamajung',
    patientMemoryBook: 'Shiranger Noksa Kaket',
    memoryBookSubtitle: 'Shiranger pelatsü asoshi noksa enokang.',
    addTaskReminder: 'Mapang tasen yanglutsü',
    testReminderMelody: 'Atenba ken asadangang 🎵',
    stopMelody: 'Ken anendakjang',
    markDone: 'Tembangogo',
    markIncomplete: 'Metembang',
    delete: 'Endokang',
    urgent: 'Teti Nüngdakba',
    melodySong: 'Atenba Ken',
    noRemindersScheduled: 'Bilemtettsü kecha maka.',
    saveMemory: 'Yutang',
    cancel: 'Meyipang',
    backToDashboard: 'Dashboard-i meyipang',
    improving: 'Renloka Odar',
    stable: 'Koma Ka Nung',
    needsAttention: 'Reprangtsü Nüngdaka',
    familyEmergency: 'Kibong aser Doctor Den Jembitsü',
    callDoctor: 'Dr. Chen dang call süang',
    callDaughter: 'Jala Sarah dang call süang',
    needHelpAnytime: 'Yariba nüngdakra tetsungda nembang.',
    tapAnyCard: 'Tenzüktsü asoshi nembang',
  },

  // Kokborok - Tripura
  trp: {
    goodMorning: 'Kaham Sal (Good morning)',
    goodAfternoon: 'Kaham Belasi (Good afternoon)',
    goodEvening: 'Kaham Sanja (Good evening)',
    todaysActivities: 'Tini-ni Samung',
    playMemoryGame: 'Uanama Kalmu',
    startGame: 'Kalmu Chenggo',
    gameDesc: 'Buku kaham khe tonani bagui kalmu.',
    myMemories: 'Ani Uanamarok',
    openPhotoBook: 'Photo Bijap Phiyo',
    memoriesDesc: 'Nokharno photo tei uanama rog.',
    voiceCameraAI: 'Kok tei Camera AI',
    voiceCameraDesc: 'Buri botol photo khula tei AI bai kok sao.',
    askAI: 'AI Yaphangno Swng',
    myReminders: 'Ani Uansukmanirok',
    viewAllReminders: 'Uansukmani jotono nai',
    remindersDesc: 'Buri chani tei twi nungni sal-samung.',
    allDone: 'Tini-ni samung paibaika',
    todaysProgress: 'Tini-ni Tangsal',
    memory: 'Uanama',
    attention: 'Naimani',
    recall: 'Uanapilmani',
    overallHealth: 'Buku-ni Skor',
    adaptiveLevel: 'Chungsa Phwl',
    easy: 'Gojon (Easy)',
    medium: 'Bwsala (Medium)',
    hard: 'Krak (Hard)',
    voiceActive: 'Kok yaphang tongo',
    readAloud: 'Phori Khwnau',
    audioHelp: 'Kok Yariba',
    listening: 'Khwna-tongo...',
    tapToSpeak: 'Kok sanani nang',
    disclaimer: 'MindCare wngkha uanama hamkraini platform.',
    patientOverview: 'Khumbar Naimani',
    gamePerformance: 'Kalmu-ni Skor',
    progressTrends: 'Hamkrai Lam',
    memoryBook: 'Photo Bijap',
    reminders: 'Uansukmani',
    addMemory: 'Ktal photo hapkhor',
    createReminder: 'Ktal uansukmani swnam',
    caregiverDashboard: 'Caregiver Dashboard',
    patientDashboard: 'Patient Dashboard',
    caregiverPortal: 'Nairoknai Portal',
    monitoringAndCare: 'Naimani tei Hamkrani:',
    caregiverSubtitle: 'Kalmu-ni skor naidi tei sal-samung swnamdi.',
    activePatient: 'Tini-ni Bedek',
    adaptiveDifficulty: 'Krak Phwl Khano',
    gentle: 'Gojon',
    balanced: 'Bwsala',
    advanced: 'Krak',
    signOut: 'Ongkhor (Sign Out)',
    gameAnalyticsTrends: 'Kalmu Bijirmani',
    clinicalPerformanceReport: 'Hamkrai Report',
    scheduleReminders: 'Sal tei Uansukmani',
    careInsightsAISummary: 'AI Upodesh',
    overallCognitiveIndex: 'Joto Uanama Index',
    visualRetention: 'Naimani Uanama',
    avgProcessingSpeed: 'Kok Phirmani Krak',
    routineAdherenceRate: 'Sal-samung Mangani',
    compositeIndexDesc: 'Buku tei uanama bil',
    retentionDesc: 'Photo uanapilmani sokoli',
    processingSpeedDesc: 'Kok phirmani samung',
    adherenceDesc: 'Buri chani tei twi nungni',
    clinicalAssessmentHeading: 'AI Buku Bijirmani',
    clinicalAssessmentSub: 'Kalmu-ni skor naikhwlai AI bijirmani.',
    listenAloud: 'Khwnau',
    stopVoice: 'Kok tono',
    copySummary: 'Copy khlai',
    exportPrintReport: 'Print Report',
    cognitiveDomainBreakdown: 'Buku-ni Bakrog',
    visualMemory: 'Naimani Uanama',
    workingMemory: 'Samung Uanama',
    executiveFunction: 'Swnamni Bil',
    processingSpeed: 'Krakni Bil',
    observedStrengths: 'Kaham Bakrog',
    areasToSupport: 'Yaritsü Nüngdaka',
    clinicalRecommendations: 'Nairoknaino Upodesh',
    accuracyProgressTrend: 'Sokoli Hamkramani',
    responseTimeBySession: 'Phirma-ni Samung',
    recentSessionLog: 'Gwdal Kalmurog',
    sessionsLogged: 'Kalmu paibaika',
    allGames: 'Joto Kalmu',
    filterByGame: 'Kalmu khano',
    dateTime: 'Sal tei Samung',
    cognitiveGame: 'Kalmu-ni Mung',
    difficulty: 'Krak Phwl',
    score: 'Skor',
    accuracy: 'Sokoli (%)',
    responseTime: 'Samung',
    mistakes: 'Gwlwi',
    patientMemoryBook: 'Photo Bijap',
    memoryBookSubtitle: 'Bedekno tong-thok khlaina photo toni.',
    addTaskReminder: 'Ktal uansukmani swnam',
    testReminderMelody: 'Sur khwnau 🎵',
    stopMelody: 'Sur tono',
    markDone: 'Paibaika',
    markIncomplete: 'Paikho',
    delete: 'Khumu',
    urgent: 'Nangmungtwi',
    melodySong: 'Sur Rwchapma',
    noRemindersScheduled: 'Uansukmani kwrwi.',
    saveMemory: 'Toni',
    cancel: 'Khumudi',
    backToDashboard: 'Dashboard-o phai',
    improving: 'Hamkrai-tongo',
    stable: 'Tik tongo',
    needsAttention: 'Nang-mungtwi',
    familyEmergency: 'Nok tei Doctor-no Phone',
    callDoctor: 'Dr. Chen-no ring',
    callDaughter: 'Bwsajw Sarah-no ring',
    needHelpAnytime: 'Yaphang nangba saikha buton nang.',
    tapAnyCard: 'Chengnani nang',
  },

  // Hindi (हिन्दी)
  hi: {
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    todaysActivities: 'आज की गतिविधियाँ',
    playMemoryGame: 'मेमोरी खेल खेलें',
    startGame: 'खेल शुरू करें',
    gameDesc: 'मन को शांत, सक्रिय और जीवंत बनाए रखने के लिए सुखद पहेलियाँ खेलें।',
    myMemories: 'मेरी यादें',
    openPhotoBook: 'फोटो एलबम खोलें',
    memoriesDesc: 'पारिवारिक यात्राओं, प्रियजनों और संजोई गई पुरानी यादों को देखें।',
    voiceCameraAI: 'वॉयस और कैमरा एआई',
    voiceCameraDesc: 'दवाइयों की बोतलें या घड़ी कैमरे से दिखाएं और अपने एआई साथी से बात करें।',
    askAI: 'एआई साथी से पूछें',
    myReminders: 'मेरे अनुस्मारक',
    viewAllReminders: 'सभी अनुस्मारक देखें',
    remindersDesc: 'दवाइयों का समय, पानी पीने और दैनिक कार्यों को समय पर पूरा करें।',
    allDone: 'आज के सभी अनुस्मारक पूरे हो चुके हैं',
    todaysProgress: 'आज की प्रगति',
    memory: 'स्मृति',
    attention: 'एकाग्रता',
    recall: 'याददाश्त',
    overallHealth: 'संज्ञानात्मक स्कोर',
    adaptiveLevel: 'कठिनाई स्तर',
    easy: 'सरल (Easy)',
    medium: 'मध्यम (Medium)',
    hard: 'कठिन (Hard)',
    voiceActive: 'आवाज सहायता सक्रिय',
    readAloud: 'बोलकर सुनाएं',
    audioHelp: 'ऑडियो सहायता',
    listening: 'सुन रहे हैं...',
    tapToSpeak: 'बोलने के लिए स्पर्श करें',
    disclaimer: 'माइंडकेयर एक सहायक स्मृति और संज्ञानात्मक प्रशिक्षण मंच है। यह किसी भी चिकित्सा निदान का विकल्प नहीं है।',
    patientOverview: 'रोगी का अवलोकन',
    gamePerformance: 'खेल प्रदर्शन',
    progressTrends: 'प्रगति के रुझान',
    memoryBook: 'स्मृति एल्बम',
    reminders: 'अनुस्मारक',
    addMemory: 'नई स्मृति जोड़ें',
    createReminder: 'अनुस्मारक बनाएं',
    caregiverDashboard: 'देखभालकर्ता डैशबोर्ड',
    patientDashboard: 'रोगी डैशबोर्ड',
    caregiverPortal: 'केयरगिवर साथी पोर्टल',
    monitoringAndCare: 'देखभाल व निगरानी:',
    caregiverSubtitle: 'गेमिंग प्रदर्शन ट्रैक करें, कठिनाई स्तर अनुकूलित करें, यादों को समृद्ध करें और दैनिक दिनचर्या निर्धारित करें।',
    activePatient: 'सक्रिय मरीज',
    adaptiveDifficulty: 'चुनौती का स्तर चुनें',
    gentle: 'सरल',
    balanced: 'संतुलित',
    advanced: 'कठिन',
    signOut: 'साइन आउट (Sign Out)',
    gameAnalyticsTrends: 'गेम विश्लेषण और रुझान',
    clinicalPerformanceReport: 'क्लिनिकल प्रदर्शन रिपोर्ट',
    scheduleReminders: 'शेड्यूल और अनुस्मारक',
    careInsightsAISummary: 'एआई देखभाल सुझाव',
    overallCognitiveIndex: 'समग्र संज्ञानात्मक सूचकांक',
    visualRetention: 'दृश्य स्मृति धारण',
    avgProcessingSpeed: 'औसत प्रतिक्रिया समय',
    routineAdherenceRate: 'दिनचर्या पालन दर',
    compositeIndexDesc: 'समग्र मानसिक स्वास्थ्य एवं धारण क्षमता',
    retentionDesc: 'फोटो और पैटर्न याद रखने की सटीकता',
    processingSpeedDesc: 'प्रति खेल प्रतिक्रिया गति',
    adherenceDesc: 'दवा, पानी और दैनिक नियम पालन',
    clinicalAssessmentHeading: 'एआई संज्ञानात्मक मूल्यांकन और क्लिनिकल रुझान',
    clinicalAssessmentSub: 'गेमिंग सटीकता व त्रुटियों का कृत्रिम बुद्धिमत्ता द्वारा विश्लेषण।',
    listenAloud: 'बोलकर सुनाएं',
    stopVoice: 'आवाज रोकें',
    copySummary: 'सारांश कॉपी करें',
    exportPrintReport: 'रिपोर्ट प्रिंट / डाउनलोड करें',
    cognitiveDomainBreakdown: 'संज्ञानात्मक डोमेन विवरण',
    visualMemory: 'दृश्य स्मृति',
    workingMemory: 'सक्रिय स्मृति',
    executiveFunction: 'कार्यकारी निर्णय क्षमता',
    processingSpeed: 'प्रसंस्करण गति',
    observedStrengths: 'मजबूत पहलू',
    areasToSupport: 'सहायता हेतु सुझाए गए क्षेत्र',
    clinicalRecommendations: 'देखभालकर्ता हेतु क्रियात्मक सुझाव',
    accuracyProgressTrend: 'सटीकता और स्कोर की प्रगति',
    responseTimeBySession: 'सत्रवार प्रतिक्रिया समय',
    recentSessionLog: 'हाल के खेल सत्र',
    sessionsLogged: 'कुल खेल सत्र',
    allGames: 'सभी खेल',
    filterByGame: 'खेल अनुसार फ़िल्टर करें',
    dateTime: 'दिनांक और समय',
    cognitiveGame: 'खेल का नाम',
    difficulty: 'कठिनाई',
    score: 'स्कोर',
    accuracy: 'सटीकता (%)',
    responseTime: 'समय',
    mistakes: 'गलतियाँ',
    patientMemoryBook: 'रोगी स्मृति एल्बम',
    memoryBookSubtitle: 'रोगी के मानसिक सुख व स्मृति पुनरुद्धार के लिए सुखद तस्वीरें संजोएं।',
    addTaskReminder: 'नया कार्य / अनुस्मारक जोड़ें',
    testReminderMelody: 'मधुर धुन सुनें 🎵',
    stopMelody: 'धुन बंद करें',
    markDone: 'पूरा हुआ',
    markIncomplete: 'अपूर्ण',
    delete: 'हटाएं',
    urgent: 'अति आवश्यक',
    melodySong: 'मधुर संगीत',
    noRemindersScheduled: 'इस मरीज के लिए कोई अनुस्मारक निर्धारित नहीं है।',
    saveMemory: 'सुरक्षित करें',
    cancel: 'रद्द करें',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    improving: 'सुधार हो रहा है',
    stable: 'स्थिर',
    needsAttention: 'ध्यान देने योग्य',
    familyEmergency: 'परिवार व डॉक्टर आपातकालीन संपर्क',
    callDoctor: 'डॉक्टर चेन को कॉल करें',
    callDaughter: 'बेटी सारा को कॉल करें',
    needHelpAnytime: 'किसी भी सहायता के लिए ऊपर दिए गए बटन को तुरंत दबाएं।',
    tapAnyCard: 'शुरू करने के लिए किसी भी कार्ड पर स्पर्श करें',
    patientLocation: 'रोगी की लोकेशन और सुरक्षित दायरा',
    locationTracking: 'लोकेशन ट्रैकिंग',
    liveLocation: 'लाइव लोकेशन',
    insideSafeZone: 'सुरक्षित दायरे में — घर पर सुरक्षित',
    outsideSafeZone: 'सुरक्षित दायरे से बाहर — भटकने की चेतावनी',
    viewOnGoogleMaps: 'गूगल मैप्स पर देखें',
    getDirections: 'रास्ता देखें',
    pingLocationNow: 'डिवाइस से ताज़ा लोकेशन लें',
    pushedFreshLocation: 'ताज़ा जीपीएस लोकेशन प्राप्त हुई',
    safeZoneRadius: 'सुरक्षित दायरा (जियोफेंस)',
    deviceBattery: 'बैटरी स्तर',
    gpsAccuracy: 'जीपीएस सटीकता',
    lastLocationUpdate: 'अंतिम अपडेट',
    recentLocationHistory: 'हाल की लोकेशन और चेक-इन इतिहास',
    patientProtectedByTracking: 'सुरक्षित दायरा सक्रिय',
    locationSharedWithCaregiver: 'आपकी लोकेशन परिवार और देखभालकर्ता द्वारा सुरक्षित रूप से मॉनिटर की जा रही है।',
    safeAtHome: 'घर पर सुरक्षित',
    switchPatient: 'मरीज बदलें',
    language: 'भाषा (Language)',
    selectLanguage: 'भाषा चुनें',
    accessibility: 'पहुंच और सुविधा (Accessibility)',
    textSize: 'अक्षर का आकार',
    highContrast: 'उच्च कंट्रास्ट',
    voiceAssistance: 'ध्वनि सहायता',
    simpleNavigation: 'सरल नेविगेशन',
    seniorPatientCompanion: 'वरिष्ठ नागरिक एवं मरीज साथी',
    caregiverFamilyPortal: 'देखभालकर्ता एवं परिवार पोर्टल',
    activeSession: 'सक्रिय सत्र',
    signIn: 'साइन इन',
    createAccount: 'खाता बनाएं',
    accountAuthDb: 'खाता और डेटाबेस',
    memoryCognitiveCompanion: 'स्मृति और संज्ञानात्मक साथी',
    bollywoodClassics: 'बॉलीवुड सदाबहार गीत',
    northEastSongs: 'पूर्वोत्तर की मधुर धुनें व लोकगीत',
    indianClassical: 'भारतीय शास्त्रीय संगीत व बांसुरी',
    myFavorites: 'मेरे पसंदीदा गीत',
    nowPlaying: 'अब बज रहा है',
    paused: 'रुका हुआ',
    tapToPlay: 'बजाने के लिए टैप करें',
    selectSongToBegin: 'शुरू करने के लिए कोई गीत चुनें',
    peacefulMelodies: 'शांत व मधुर धुनें',
    songLibraryPlaylists: 'गीत संग्रह व प्लेलिस्ट',
    showingComfortSongs: 'सुकून भरे गीत',
    noSongsInCategory: 'इस श्रेणी में कोई गीत नहीं मिला',
    addSongPrompt: 'नीचे दिए गए बटन से अपनी पसंद का कोई भी गीत जोड़ें।',
    readStory: 'कहानी पढ़कर सुनाएं',
    cognitiveExercises: 'संज्ञानात्मक खेल व अभ्यास',
    cognitiveExercisesDesc: 'मन को शांत और सक्रिय रखने के लिए नीचे दिए गए सरल खेलों में से चुनें।',
    memoryMatch: 'मेमोरी मैच (जोड़ी मिलाएँ)',
    memoryMatchDesc: 'कार्ड पलटें और फूलों, पालतू जानवरों व फलों की जोड़ियाँ बनाएँ।',
    visualAssociation: 'दृश्य संज्ञान',
    pictureRecall: 'चित्र स्मरण (Picture Recall)',
    pictureRecallDesc: 'चित्रों को ध्यान से देखें और पहचानें कि कौन सा चित्र दिखाया गया था।',
    shortTermRecall: 'अल्पकालिक स्मृति',
    numberRecall: 'अंक स्मरण (Number Recall)',
    numberRecallDesc: 'संख्याओं को देखें और बड़े बटनों की सहायता से टाइप करें।',
    auditoryWorkingMemory: 'श्रवण व कार्यशील स्मृति',
    patternRecognition: 'पैटर्न पहचान (Pattern Recognition)',
    patternRecognitionDesc: 'आकृतियों और रंगों का सही क्रम पहचान कर खाली जगह भरें।',
    logicalFocus: 'तार्किक एकाग्रता',
    adaptiveSystem: 'अनुकूली प्रणाली (Adaptive System)',
    playNow: 'अभी खेलें',
    playAgain: 'फिर से खेलें',
    backToHub: 'खेल मेनू पर लौटें',
    restart: 'पुनः आरंभ करें',
    tries: 'प्रयास',
    level: 'स्तर',
    takeYourTime: 'कार्ड पर टैप करके सही जोड़ी खोजें। पूरा समय लें!',
    splendidGameComplete: 'शानदार! खेल पूरा हुआ!',
    matchedAllCards: 'आपने सभी कार्ड सफलतापूर्वक मिला लिए हैं।',
    whichItemWasInPictures: 'आपने अभी कौन सा चित्र देखा था?',
    chooseMatchingItem: 'वह चित्र चुनें जो आपने कुछ देर पहले देखा था।',
    brilliantCorrect: 'बिल्कुल सही! बहुत बढ़िया याद रखा।',
    goodEffort: 'अच्छा प्रयास! सही उत्तर था',
    nextRound: 'अगला राउंड',
    completeExercise: 'अभ्यास पूरा करें',
    studyCarefully: 'चित्रों को ध्यानपूर्वक देखें',
    readyToRecall: 'उत्तर देने के लिए तैयार? तैयार होने पर दबाएं।',
    beginRecall: 'उत्तर देना शुरू करें',
    rememberTheseNumbers: 'इन संख्याओं को याद रखें',
    nowEnterNumbers: 'अब वे संख्याएँ दर्ज करें जो आपने देखी थीं',
    clear: 'हटाएं',
    checkAnswer: 'उत्तर जांचें',
    whatComesNextInPattern: 'इस क्रम में आगे क्या आएगा?',
    tapCorrectMissingShape: 'क्रम पूरा करने के लिए सही आकृति पर टैप करें।',
    allReminders: 'सभी',
    medications: 'दवाइयाँ',
    hydration: 'पानी पीना',
    activity: 'व्यायाम व सैर',
    dailyTasks: 'दैनिक कार्य',
    completedTasks: 'पूर्ण हुआ',
    activeReminders: 'सक्रिय अनुस्मारक',
    addNewReminder: 'नया कार्य या अनुस्मारक जोड़ें',
    takeWithWater: 'एक गिलास पानी के साथ लें',
    dueNow: 'अभी का समय',
    upcoming: 'आगामी',
  },

  // Spanish (Español)
  es: {
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    todaysActivities: 'Actividades de hoy',
    playMemoryGame: 'Jugar Juego de Memoria',
    startGame: 'Comenzar Juego',
    gameDesc: 'Disfruta de rompecabezas relajantes para mantener tu mente activa.',
    myMemories: 'Mis Recuerdos',
    openPhotoBook: 'Abrir Álbum de Fotos',
    memoriesDesc: 'Explora fotos familiares, viajes y recuerdos preciados.',
    voiceCameraAI: 'Voz y Cámara IA',
    voiceCameraDesc: 'Muestra frascos de medicina o relojes a la cámara y habla con tu asistente.',
    askAI: 'Consultar al Asistente IA',
    myReminders: 'Mis Recordatorios',
    viewAllReminders: 'Ver todos los recordatorios',
    remindersDesc: 'Horarios de medicación, hidratación y tareas diarias.',
    allDone: 'Todos los recordatorios completados por hoy',
    todaysProgress: 'Progreso de Hoy',
    memory: 'Memoria',
    attention: 'Atención',
    recall: 'Retención',
    overallHealth: 'Puntaje Cognitivo',
    adaptiveLevel: 'Nivel de Desafío',
    easy: 'Suave (Fácil)',
    medium: 'Equilibrado (Medio)',
    hard: 'Avanzado (Difícil)',
    voiceActive: 'Ayuda por voz activa',
    readAloud: 'Leer en voz alta',
    audioHelp: 'Ayuda de Audio',
    listening: 'Escuchando...',
    tapToSpeak: 'Toca para hablar',
    disclaimer: 'MindCare es una plataforma asistiva de memoria y estimulación cognitiva.',
    patientOverview: 'Resumen del Paciente',
    gamePerformance: 'Rendimiento en Juegos',
    progressTrends: 'Tendencias de Progreso',
    memoryBook: 'Álbum de Recuerdos',
    reminders: 'Recordatorios',
    addMemory: 'Añadir Nuevo Recuerdo',
    createReminder: 'Crear Recordatorio',
    caregiverDashboard: 'Panel del Cuidador',
    patientDashboard: 'Panel del Paciente',
    caregiverPortal: 'Portal del Cuidador',
    monitoringAndCare: 'Monitoreo y Cuidado para:',
    caregiverSubtitle: 'Rastrea el rendimiento cognitivo, enriquece el álbum y programa recordatorios diarios.',
    activePatient: 'Paciente Activo',
    adaptiveDifficulty: 'Nivel de Dificultad Adaptativo',
    gentle: 'Suave',
    balanced: 'Equilibrado',
    advanced: 'Avanzado',
    signOut: 'Cerrar Sesión',
    gameAnalyticsTrends: 'Analíticas y Tendencias',
    clinicalPerformanceReport: 'Informe Clínico de Rendimiento',
    scheduleReminders: 'Horarios y Recordatorios',
    careInsightsAISummary: 'Perspectivas IA y Recomendaciones',
    overallCognitiveIndex: 'Índice Cognitivo General',
    visualRetention: 'Retención Visual',
    avgProcessingSpeed: 'Velocidad de Procesamiento',
    routineAdherenceRate: 'Adherencia a la Rutina',
    compositeIndexDesc: 'Salud cognitiva compuesta y retención',
    retentionDesc: 'Precisión en reconocimiento de patrones y fotos',
    processingSpeedDesc: 'Tiempo medio de reacción por ejercicio',
    adherenceDesc: 'Cumplimiento de hidratación y medicamentos',
    clinicalAssessmentHeading: 'Evaluación Cognitiva y Tendencias IA',
    clinicalAssessmentSub: 'Análisis automatizado de precisión, patrones de errores y rutinas.',
    listenAloud: 'Escuchar en Voz Alta',
    stopVoice: 'Detener Voz',
    copySummary: 'Copiar Resumen',
    exportPrintReport: 'Imprimir / Exportar Informe',
    cognitiveDomainBreakdown: 'Desglose de Dominios Cognitivos',
    visualMemory: 'Memoria Visual',
    workingMemory: 'Memoria de Trabajo',
    executiveFunction: 'Función Ejecutiva',
    processingSpeed: 'Velocidad de Procesamiento',
    observedStrengths: 'Fortalezas Observadas',
    areasToSupport: 'Áreas de Apoyo Recomendadas',
    clinicalRecommendations: 'Recomendaciones Prácticas',
    accuracyProgressTrend: 'Tendencia de Precisión y Puntos',
    responseTimeBySession: 'Tiempo de Respuesta por Sesión',
    recentSessionLog: 'Registro de Sesiones Recientes',
    sessionsLogged: 'Sesiones Registradas',
    allGames: 'Todos los Juegos',
    filterByGame: 'Filtrar por Juego',
    dateTime: 'Fecha y Hora',
    cognitiveGame: 'Juego',
    difficulty: 'Dificultad',
    score: 'Puntos',
    accuracy: 'Precisión (%)',
    responseTime: 'Tiempo',
    mistakes: 'Errores',
    patientMemoryBook: 'Álbum de Recuerdos del Paciente',
    memoryBookSubtitle: 'Añade fotos reconfortantes para estimular recuerdos entrañables.',
    addTaskReminder: 'Añadir Recordatorio / Tarea',
    testReminderMelody: 'Probar Melodía 🎵',
    stopMelody: 'Detener Melodía',
    markDone: 'Completar',
    markIncomplete: 'Incompleto',
    delete: 'Eliminar',
    urgent: 'Urgente',
    melodySong: 'Canción Melódica',
    noRemindersScheduled: 'No hay recordatorios programados para este paciente.',
    saveMemory: 'Guardar',
    cancel: 'Cancelar',
    backToDashboard: 'Volver al Panel',
    improving: 'Mejorando',
    stable: 'Estable',
    needsAttention: 'Requiere Atención',
    familyEmergency: 'Contactos de Emergencia Familiar',
    callDoctor: 'Llamar al Dr. Chen',
    callDaughter: 'Llamar a Hija (Sarah)',
    needHelpAnytime: 'Si necesitas ayuda, toca cualquiera de los botones de arriba.',
    tapAnyCard: 'Toca cualquier tarjeta para comenzar',
  },

  // French (Français)
  fr: {
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    todaysActivities: "Activités d'aujourd'hui",
    playMemoryGame: 'Jouer au Jeu de Mémoire',
    startGame: 'Commencer le Jeu',
    gameDesc: 'Des puzzles apaisants pour stimuler votre esprit en douceur.',
    myMemories: 'Mes Souvenirs',
    openPhotoBook: 'Ouvrir Album Photo',
    memoriesDesc: 'Parcourez les photos de famille et vos moments précieux.',
    voiceCameraAI: 'IA Vocale & Caméra',
    voiceCameraDesc: 'Montrez des flacons ou horloges à la caméra et conversez naturellement.',
    askAI: 'Consulter le Compagnon IA',
    myReminders: 'Mes Rappels',
    viewAllReminders: 'Voir tous les rappels',
    remindersDesc: 'Médicaments, hydratation et tâches quotidiennes.',
    allDone: 'Tous les rappels sont terminés pour aujourd’hui',
    todaysProgress: "Progrès d'Aujourd'hui",
    memory: 'Mémoire',
    attention: 'Attention',
    recall: 'Rappel',
    overallHealth: 'Score Cognitif',
    adaptiveLevel: 'Niveau de Défi',
    easy: 'Doux (Facile)',
    medium: 'Équilibré (Moyen)',
    hard: 'Avancé (Difficile)',
    voiceActive: 'Aide vocale active',
    readAloud: 'Lire à voix haute',
    audioHelp: 'Aide Audio',
    listening: 'Écoute en cours...',
    tapToSpeak: 'Toucher pour parler',
    disclaimer: 'MindCare est une plateforme d’assistance et de stimulation cognitive.',
    patientOverview: 'Aperçu du Patient',
    gamePerformance: 'Performances des Jeux',
    progressTrends: 'Tendances du Progrès',
    memoryBook: 'Livre des Souvenirs',
    reminders: 'Rappels',
    addMemory: 'Ajouter un Souvenir',
    createReminder: 'Créer un Rappel',
    caregiverDashboard: 'Tableau de Bord Soignant',
    patientDashboard: 'Tableau de Bord Patient',
    caregiverPortal: 'Portail du Soignant',
    monitoringAndCare: 'Suivi et Soins pour :',
    caregiverSubtitle: 'Suivez les performances cognitives, enrichissez l’album photo et planifiez les rappels.',
    activePatient: 'Patient Actif',
    adaptiveDifficulty: 'Niveau de Défi Adaptatif',
    gentle: 'Doux',
    balanced: 'Équilibré',
    advanced: 'Avancé',
    signOut: 'Se Déconnecter',
    gameAnalyticsTrends: 'Analytiques et Tendances',
    clinicalPerformanceReport: 'Rapport Clinique de Performance',
    scheduleReminders: 'Planning et Rappels',
    careInsightsAISummary: 'Conseils & Analyse IA',
    overallCognitiveIndex: 'Indice Cognitif Global',
    visualRetention: 'Rétention Visuelle',
    avgProcessingSpeed: 'Vitesse de Traitement',
    routineAdherenceRate: 'Adhésion à la Routine',
    compositeIndexDesc: 'Indice de santé cognitive et de rétention',
    retentionDesc: 'Précision de reconnaissance des photos et motifs',
    processingSpeedDesc: 'Temps de réaction moyen par exercice',
    adherenceDesc: 'Hydratation et prise ponctuelle des médicaments',
    clinicalAssessmentHeading: 'Évaluation Clinique & Tendances IA',
    clinicalAssessmentSub: 'Analyse IA des performances de jeu et de l’engagement quotidien.',
    listenAloud: 'Écouter à voix haute',
    stopVoice: 'Arrêter la Voix',
    copySummary: 'Copier le Résumé',
    exportPrintReport: 'Imprimer / Exporter le Rapport',
    cognitiveDomainBreakdown: 'Domaines Cognitifs Détaillés',
    visualMemory: 'Mémoire Visuelle',
    workingMemory: 'Mémoire de Travail',
    executiveFunction: 'Fonction Exécutive',
    processingSpeed: 'Vitesse de Traitement',
    observedStrengths: 'Forces Observées',
    areasToSupport: 'Points à Soutenir',
    clinicalRecommendations: 'Recommandations pour le Soignant',
    accuracyProgressTrend: 'Progression de la Précision',
    responseTimeBySession: 'Temps de Réponse par Session',
    recentSessionLog: 'Journal des Sessions Récentes',
    sessionsLogged: 'Sessions Enregistrées',
    allGames: 'Tous les Jeux',
    filterByGame: 'Filtrer par Jeu',
    dateTime: 'Date & Heure',
    cognitiveGame: 'Jeu',
    difficulty: 'Difficulté',
    score: 'Score',
    accuracy: 'Précision (%)',
    responseTime: 'Temps',
    mistakes: 'Erreurs',
    patientMemoryBook: 'Livre de Souvenirs du Patient',
    memoryBookSubtitle: 'Ajoutez des photos apaisantes pour stimuler les souvenirs.',
    addTaskReminder: 'Ajouter une Tâche / Rappel',
    testReminderMelody: 'Tester la Mélodie 🎵',
    stopMelody: 'Arrêter la Mélodie',
    markDone: 'Terminé',
    markIncomplete: 'Incomplet',
    delete: 'Supprimer',
    urgent: 'Urgent',
    melodySong: 'Chanson Mélodieuse',
    noRemindersScheduled: 'Aucun rappel prévu pour ce patient.',
    saveMemory: 'Enregistrer',
    cancel: 'Annuler',
    backToDashboard: 'Retour au Tableau de Bord',
    improving: 'En Amélioration',
    stable: 'Stable',
    needsAttention: 'Nécessite Attention',
    familyEmergency: 'Contacts d’Urgence & Famille',
    callDoctor: 'Appeler Dr. Chen',
    callDaughter: 'Appeler Fille (Sarah)',
    needHelpAnytime: 'Pour toute aide, appuyez immédiatement sur les boutons ci-dessus.',
    tapAnyCard: 'Touchez une carte pour commencer',
  },

  // German (Deutsch)
  de: {
    goodMorning: 'Guten Morgen',
    goodAfternoon: 'Guten Tag',
    goodEvening: 'Guten Abend',
    todaysActivities: 'Heutige Aktivitäten',
    playMemoryGame: 'Gedächtnisspiel spielen',
    startGame: 'Spiel starten',
    gameDesc: 'Beruhigende Denksportaufgaben zur sanften geistigen Förderung.',
    myMemories: 'Meine Erinnerungen',
    openPhotoBook: 'Fotoalbum öffnen',
    memoriesDesc: 'Bilder von Familienausflügen und wertvollen Erinnerungen ansehen.',
    voiceCameraAI: 'Sprach- & Kamera-KI',
    voiceCameraDesc: 'Medikamentenflaschen oder Uhren per Kamera zeigen und sprechen.',
    askAI: 'KI-Begleiter fragen',
    myReminders: 'Meine Erinnerungen',
    viewAllReminders: 'Alle Erinnerungen anzeigen',
    remindersDesc: 'Medikamente, Trinken und tägliche Routinen im Blick behalten.',
    allDone: 'Alle Erinnerungen für heute erledigt',
    todaysProgress: 'Heutiger Fortschritt',
    memory: 'Gedächtnis',
    attention: 'Aufmerksamkeit',
    recall: 'Erinnerungsvermögen',
    overallHealth: 'Kognitiver Wert',
    adaptiveLevel: 'Schwierigkeitsgrad',
    easy: 'Sanft (Einfach)',
    medium: 'Ausgewogen (Mittel)',
    hard: 'Fortgeschritten (Schwer)',
    voiceActive: 'Sprachhilfe aktiv',
    readAloud: 'Vorlesen',
    audioHelp: 'Audio-Hilfe',
    listening: 'Hört zu...',
    tapToSpeak: 'Tippen zum Sprechen',
    disclaimer: 'MindCare ist eine unterstützende Gedächtnis- und kognitive Trainingsplattform.',
    patientOverview: 'Patientenübersicht',
    gamePerformance: 'Spielleistung',
    progressTrends: 'Fortschrittstrends',
    memoryBook: 'Erinnerungsbuch',
    reminders: 'Erinnerungen',
    addMemory: 'Neue Erinnerung hinzufügen',
    createReminder: 'Erinnerung erstellen',
    caregiverDashboard: 'Pflegekraft-Dashboard',
    patientDashboard: 'Patienten-Dashboard',
    caregiverPortal: 'Pflege-Begleitportal',
    monitoringAndCare: 'Überwachung & Betreuung für:',
    caregiverSubtitle: 'Kognitive Leistungen verfolgen, Erinnerungsalben pflegen und Termine planen.',
    activePatient: 'Aktiver Patient',
    adaptiveDifficulty: 'Anpassbare Herausforderung',
    gentle: 'Sanft',
    balanced: 'Ausgewogen',
    advanced: 'Fortgeschritten',
    signOut: 'Abmelden',
    gameAnalyticsTrends: 'Spielanalyse & Trends',
    clinicalPerformanceReport: 'Klinischer Leistungsbericht',
    scheduleReminders: 'Termine & Erinnerungen',
    careInsightsAISummary: 'KI-Pflegehinweise & Empfehlungen',
    overallCognitiveIndex: 'Gesamter Kognitionsindex',
    visualRetention: 'Visuelle Merkfähigkeit',
    avgProcessingSpeed: 'Durchschnittliche Reaktionszeit',
    routineAdherenceRate: 'Routinetreue',
    compositeIndexDesc: 'Zusammengesetzter Wert für geistige Fitness und Erinnerung',
    retentionDesc: 'Genauigkeit bei Foto- und Musterwiedererkennung',
    processingSpeedDesc: 'Durchschnittliche Reaktionszeit pro Aufgabe',
    adherenceDesc: 'Regelmäßiges Trinken und pünktliche Medikamenteneinnahme',
    clinicalAssessmentHeading: 'KI-Kognitionsbewertung & klinische Trends',
    clinicalAssessmentSub: 'Automatisierte KI-Auswertung der Genauigkeit und Fehleranalysen.',
    listenAloud: 'Laut Vorlesen',
    stopVoice: 'Sprache stoppen',
    copySummary: 'Zusammenfassung kopieren',
    exportPrintReport: 'Bericht drucken / exportieren',
    cognitiveDomainBreakdown: 'Kognitive Bereiche im Detail',
    visualMemory: 'Visuelles Gedächtnis',
    workingMemory: 'Arbeitsgedächtnis',
    executiveFunction: 'Exekutive Funktionen',
    processingSpeed: 'Verarbeitungsgeschwindigkeit',
    observedStrengths: 'Beobachtete Stärken',
    areasToSupport: 'Empfohlene Förderbereiche',
    clinicalRecommendations: 'Praktische Handlungsempfehlungen',
    accuracyProgressTrend: 'Genauigkeits- und Punkteverlauf',
    responseTimeBySession: 'Reaktionszeit nach Sitzung',
    recentSessionLog: 'Protokoll der letzten Sitzungen',
    sessionsLogged: 'Protokollierte Sitzungen',
    allGames: 'Alle Spiele',
    filterByGame: 'Nach Spiel filtern',
    dateTime: 'Datum & Uhrzeit',
    cognitiveGame: 'Spiel',
    difficulty: 'Schwierigkeit',
    score: 'Punkte',
    accuracy: 'Genauigkeit (%)',
    responseTime: 'Zeit',
    mistakes: 'Fehler',
    patientMemoryBook: 'Patienten-Erinnerungsbuch',
    memoryBookSubtitle: 'Fotos zur seelischen Unterstützung und Erinnerungsförderung einfügen.',
    addTaskReminder: 'Aufgabe / Erinnerung hinzufügen',
    testReminderMelody: 'Melodie testen 🎵',
    stopMelody: 'Melodie stoppen',
    markDone: 'Erledigt',
    markIncomplete: 'Offen',
    delete: 'Löschen',
    urgent: 'Dringend',
    melodySong: 'Melodisches Lied',
    noRemindersScheduled: 'Keine Erinnerungen für diesen Patienten geplant.',
    saveMemory: 'Speichern',
    cancel: 'Abbrechen',
    backToDashboard: 'Zurück zum Dashboard',
    improving: 'Verbessert sich',
    stable: 'Stabil',
    needsAttention: 'Aufmerksamkeit erforderlich',
    familyEmergency: 'Familien- und Notfallkontakte',
    callDoctor: 'Dr. Chen anrufen',
    callDaughter: 'Tochter Sarah anrufen',
    needHelpAnytime: 'Tippen Sie oben, um Angehörige oder Ärzte sofort zu erreichen.',
    tapAnyCard: 'Tippen Sie auf eine Karte zum Starten',
  },
};

export const LANGUAGE_ANNOUNCEMENTS: Record<LanguageOption, string> = {
  en: 'English language selected. Welcome to MindCare.',
  hi: 'हिंदी भाषा चुनी गई है। माइंडकेयर में आपका स्वागत है।',
  as: 'অসমীয়া ভাষা নিৰ্বাচিত কৰা হৈছে। মাইণ্ডকেয়াৰলৈ স্বাগতম।',
  bn: 'বাংলা ভাষা নির্বাচন করা হয়েছে। মাইন্ডকেয়ারে আপনাকে স্বাগতম।',
  mni: 'মৈতৈলোন্ খনলে। মাইণ্ডকেয়ারদা তরাম্না ওকচরি।',
  brx: "बर' राव सायख'बाय। माइन्डकेयाराव बरायबाय।",
  lus: 'Mizo ṭawng thlan a ni e. MindCare-ah kan lo lawm a che.',
  kha: 'Ka ktien Khasi la jied. Sngewbha wan sha MindCare.',
  grt: 'A·chik ku·sikko seokaha. MindCare-ona rimsoenga.',
  ne: 'नेपाली भाषा चयन गरिएको छ। माइन्डकेयरमा स्वागत छ।',
  ao: 'Ao oshi shimtetogo. MindCare dangi pelashishir.',
  trp: 'Kokborok kok rombai. MindCare-o kaisa tui manlai.',
  es: 'Idioma español seleccionado. Bienvenido a MindCare.',
  fr: 'Langue française sélectionnée. Bienvenue sur MindCare.',
  de: 'Deutsche Sprache ausgewählt. Willkommen bei MindCare.',
};

export const AccessibilityProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [fontSize, setFontSize] = useState<FontSizeOption>(() => {
    return (localStorage.getItem('mindcare_font_size') as FontSizeOption) || 'normal';
  });

  const [highContrast, setHighContrast] = useState<boolean>(() => {
    return localStorage.getItem('mindcare_high_contrast') === 'true';
  });

  const [voiceAssistance, setVoiceAssistance] = useState<boolean>(() => {
    return localStorage.getItem('mindcare_voice_assist') !== 'false';
  });

  const [speechRate, setSpeechRate] = useState<number>(() => {
    const saved = localStorage.getItem('mindcare_speech_rate');
    return saved ? parseFloat(saved) : 0.9;
  });

  const [language, setLanguageState] = useState<LanguageOption>(() => {
    return (localStorage.getItem('mindcare_lang') as LanguageOption) || 'en';
  });

  const setLanguage = (newLang: LanguageOption) => {
    setLanguageState(newLang);
    localStorage.setItem('mindcare_lang', newLang);

    // Voiceover accessibility announcement upon language selection
    const announcement =
      LANGUAGE_ANNOUNCEMENTS[newLang] || `Language set to ${newLang}. Welcome to MindCare.`;
    const localeMap: Record<LanguageOption, string> = {
      en: 'en-US',
      as: 'as-IN',
      bn: 'bn-IN',
      mni: 'mni-IN',
      brx: 'brx-IN',
      lus: 'lus-IN',
      kha: 'kha-IN',
      grt: 'grt-IN',
      ne: 'ne-NP',
      ao: 'en-IN',
      trp: 'bn-IN',
      hi: 'hi-IN',
      es: 'es-ES',
      fr: 'fr-FR',
      de: 'de-DE',
    };

    speech.speak(announcement, {
      rate: speechRate || 0.88,
      language: localeMap[newLang] || 'en-US',
    });
  };

  const [simpleNavigation, setSimpleNavigation] = useState<boolean>(() => {
    return localStorage.getItem('mindcare_simple_nav') === 'true';
  });

  useEffect(() => {
    localStorage.setItem('mindcare_font_size', fontSize);
    const root = document.documentElement;
    root.classList.remove('text-normal', 'text-large', 'text-extra-large');
    root.classList.add(`text-${fontSize}`);
  }, [fontSize]);

  useEffect(() => {
    localStorage.setItem('mindcare_high_contrast', String(highContrast));
    const root = document.documentElement;
    if (highContrast) {
      root.classList.add('high-contrast-mode');
    } else {
      root.classList.remove('high-contrast-mode');
    }
  }, [highContrast]);

  useEffect(() => {
    localStorage.setItem('mindcare_lang', language);
  }, [language]);

  const speakText = (text: string) => {
    if (!voiceAssistance) return;
    const localeMap: Record<LanguageOption, string> = {
      en: 'en-US',
      as: 'as-IN',
      bn: 'bn-IN',
      mni: 'mni-IN',
      brx: 'brx-IN',
      lus: 'lus-IN',
      kha: 'kha-IN',
      grt: 'grt-IN',
      ne: 'ne-NP',
      ao: 'en-IN',
      trp: 'bn-IN',
      hi: 'hi-IN',
      es: 'es-ES',
      fr: 'fr-FR',
      de: 'de-DE',
    };
    speech.speak(text, { rate: speechRate, language: localeMap[language] || 'en-US' });
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <AccessibilityContext.Provider
      value={{
        fontSize,
        setFontSize,
        highContrast,
        setHighContrast,
        voiceAssistance,
        setVoiceAssistance,
        speechRate,
        setSpeechRate,
        language,
        setLanguage,
        simpleNavigation,
        setSimpleNavigation,
        speakText,
        t,
      }}
    >
      {children}
    </AccessibilityContext.Provider>
  );
};

export const useAccessibility = () => {
  const context = useContext(AccessibilityContext);
  if (!context) throw new Error('useAccessibility must be used within AccessibilityProvider');
  return context;
};
